### ISSUE TITLE
Some requests

### ISSUE THREAD

**Issue by jhuriez** [Mardaneus86/futwebapp-tampermonkey#1]
Hi,

Nice scripts and nice work !

Somes features requests : 

- Show "Contract" and "Fitness" in SearchResult list
- I thinks it's not possible but : Be able to filter by minimum contract number
- Auto "BuyNow" in one click, or one shortcut ?

I have tried to create a script tampermonkey for auto focus the input text "price-filter" in Search page, but it's doesn't work.. You know if it's possible ?

**Comment by Mardaneus86** [comment]
I've splitted this into a few issues, so it's easier to track progress.

Regarding filtering by minimum contract number; that is indeed not possible, but there could be a workaround by disabling Players where the minimum contract amount you set isn't reached. Please create a new issue for this specific use case if this is something you really need/want.
