### ISSUE TITLE
Futbin price API ?

### ISSUE THREAD

**Issue by jodiejo93** [Mardaneus86/futwebapp-tampermonkey#101]
This is not so much an issue as more so a request.

I am creating an excel sheet in google sheets which led me to your post here. I was able to install and run this with no issue, but I was hoping to see if the API for grabbing the price would be extractable by itself?

I am indefinitely a noob to all this, but this has prompted my interest in learning javascript, but I guess what I am getting at here is seeing if I  can implement your search API as an " ImportJson" command in google sheets such as this video: https://www.youtube.com/watch?v=EXKhVQU37WM 

If not I understand, and the web app script works great , but my goal here is to monitor all my investments I set conditional formatting to alert me when to sell or buy.

**Comment by ajpiano** [comment]
You can look at [this section of the futbin-prices script](https://github.com/Mardaneus86/futwebapp-tampermonkey/blob/master/app/futbin/futbin-prices.js#L103-L127) to see how the extension requests the prices from Futbin's API using the resourceId. You can hit the `https://www.futbin.com/18/playerPrices?player=&all_versions` endpoint with the resourceIds of the players in your spreadsheet and get the JSON you need that way. Good luck with your JavaScripting. :)

**Comment by Mardaneus86** [comment]
@jodiejo93 feel free to relay these questions to the [Gitter channel](https://gitter.im/futwebapp-tampermonkey/Lobby) that is mentioned in the Readme to keep the issue list clean.

I think the answer above is sufficient to get you started. If not, please reach out on Gitter.

Best of luck with your learning! 🎉

**Comment by jodiejo93** [comment]
Cheers buddy,

Hopefully, this gets me down the right path.

I'll follow through on the Gitter if I have any other questions.
