### ISSUE TITLE
QUESTION Bundle all code into one file

### ISSUE THREAD

**Issue by NapStudio** [Mardaneus86/futwebapp-tampermonkey#107]
Hi,
how can I bundle all the code into one file to use it in tampermonkey?

**Comment by Mardaneus86** [comment]
You can download [the latest release](https://github.com/Mardaneus86/futwebapp-tampermonkey/releases) or build the script yourself.

Building the script yourself is explained in the [Developing section in the Readme](https://github.com/Mardaneus86/futwebapp-tampermonkey#developing). When you run these commands, you will get a `bundle.js` that is the same as what you get from the released versions.
