### ISSUE TITLE
Automatically list items such as contracts

### ISSUE THREAD

**Issue by pratik60** [Mardaneus86/futwebapp-tampermonkey#109]
Is there a way to do this? Its very boring to list each for 200

**Comment by Mardaneus86** [comment]
Possible yes, but it probably will get you flagged as a 'bot' quite fast if not implemented properly. It does require a fair amount of UI to personalize to your specific situation (which contracts to sell, at which price and how many contracts to keep, etc...)

Will keep it in mind for future versions, however currently I'm not actively developing new features.

**Comment by Mardaneus86** [comment]
Closing because automation features will not be provided in this years version.
