### ISSUE TITLE
 Futbin integration not working

### ISSUE THREAD

**Issue by JhonMaya** [Mardaneus86/futwebapp-tampermonkey#114]
Futbin integration not working

- **Script version:** 1.0.2
- **Browser:** chrome V 69.0.3497.100
- **OS:** W10

**Comment by JhonMaya** [comment]
Sorry, please closed

**Comment by Mardaneus86** [comment]
If something isn't working, try to add some more details about the behaviour that you see. For normal support questions, please use Gitter as the first channel.
