### ISSUE TITLE
Show player prices on transfer list

### ISSUE THREAD

**Issue by Kyderman** [Mardaneus86/futwebapp-tampermonkey#12]
Hi, can you show the player prices on transfer list please, I see in the code it only works in club and in transfer search

**Comment by Mardaneus86** [comment]
I'll take a look this evening. Thanks for reporting.

**Comment by Kyderman** [comment]
Hi, also, I think the player price showing has broken.

the platform stuff has broken it, is it LCCost or something is undefined (cant remember right now)

**Comment by Mardaneus86** [comment]
Can you provide an error log and state which version of the script you are using? Also which platform are you using?

It is `LCPrice` and should be available on every correct response from Futbin.

**Comment by Kyderman** [comment]
Alright champ, give me a second, ill be back with an answer in a min

**Comment by Kyderman** [comment]
Uncaught TypeError: Cannot read property 'LCPrice' of undefined
    at Function.onload (eval at E_c (:3:298), <anonymous>:53:180)
    at <anonymous>:2:479
    at eval (eval at exec_fn (:2:27), <anonymous>:31:101)

So the part that is undefined is the platform prices part call.

Using v0.1.3, was working before the update to that.

**Comment by Mardaneus86** [comment]
Alright, what is the response of this command in the developer tools console: `repositories.User.getCurrent().getSelectedPersona().platform`?

If you are using Chrome, on the right side you can see a link next to the error, it looks like `VM....:##'. That will bring you to the exact location where the exception occurs. You can set a breakpoint on that line and try to determine where it goes wrong, because I can't reproduce it here.

**Comment by Kyderman** [comment]
"XBO" is returned, so maybe that's been changed.

The error point is at

`target.append('<div class="auction" style="margin: 0; width: auto;"><span class="label">Futbin BIN</span><span class="coins value">' + data[playerId].prices[platform].LCPrice + '</span></div>');`

**Comment by Kyderman** [comment]
Oh, btw, I'm an angular 4 and node developer, and happy to help on any of this, I could fix the above myself, but I'm currently at work. In the future ill be sure to fix bugs and add features (I'm particularly interested in marking players that are currently usable in SBC's, based on SBC squads in futbin etc :)

**Comment by Mardaneus86** [comment]
Oh, I made a mistake in the update checking the xbox platform (copy/paste error). Will fix that bug immediately!

Any help is greatly appreciated.

**Comment by Mardaneus86** [comment]
The prices aren't shown on the Transfer List because it doesn't trigger the `DOMNodeInserted` event in the same way as the other screens. Feel free to do a PR for this.

**Comment by Kyderman** [comment]
If I get some time later ill get it sorted, shouldnt be too big a task
