### ISSUE TITLE
Show Futbin values on Player Pick Items

### ISSUE THREAD

**Issue by Mardaneus86** [Mardaneus86/futwebapp-tampermonkey#120]
### Expected behavior:
Should show the Futbin BIN values of players in the Player Pick Items dialog.

### Current behavior:
No Futbin prices are shown.
![Player Pick Item dialog](https://user-images.githubusercontent.com/7780108/46466901-ceb4a080-c7cc-11e8-8055-1594e1a5b954.png)

**Comment by klauskpm** [comment]
Hi. I'd like to contribute.

I didn't find any file specifying contributing steps and rules. Are there any requirements?

Also, could you give more information about the issue? Like layout specifications.

**Comment by Mardaneus86** [comment]
Thanks for reaching out. There aren't any specific contribution guidelines yet, apart from adhering to the commit history and pushing PRs to the develop branch. I still need to add those guidelines to the repository.

I've just completed this feature, and was about to push the commit. Feel free to help on other issues if you want.

![Player Item Pick screen](https://user-images.githubusercontent.com/7780108/46471112-3670e880-c7d9-11e8-80c6-dc2ceaf939e7.png)
