### ISSUE TITLE
Colorize bargain using Bid instead of BIN

### ISSUE THREAD

**Issue by DeRutterQS** [Mardaneus86/futwebapp-tampermonkey#123]
The new "colorize bargain" Feature is great but its really hard to find a player bargain nowadays. Only with the 59th minute trick and there is still a low chance to find one.

Would be awesome it would compare Futbin price with the bid price of the player and highlight if the Bid is at least 10% lower than the Futbin Price.

**Comment by Mardaneus86** [comment]
Dupe of #121.
