### ISSUE TITLE
List multiple items from club at once

### ISSUE THREAD

**Issue by Mardaneus86** [Mardaneus86/futwebapp-tampermonkey#13]
Ability to list multiple items for transfer at once, instead of setting the price and listing each item individually.

**Comment by renard0** [comment]
How do you see the whole process?

**Comment by Mardaneus86** [comment]
By adding checkboxes on each item on the tradepile (available items), you could give the user 1 input for list and bin price.

For consumables you could use the Club Search and put an amount in the ‘List for auction’ inputs.

It could call the list API with a small delay between each request as to not raise suspision.

I didn’t give this a lot of thought yet, so if anyone has a better idea I’m open for suggestions!

**Comment by renard0** [comment]
Sounds good, I think it should be relevant both for transfer and club pages.
Sending bulk from club to transfer list may also be useful

**Comment by Mardaneus86** [comment]
I could, but I have other priorities right now. If anyone wants to take a stab at this feature, feel free to do a PR.

**Comment by renard0** [comment]
Assign me to this feature

**Comment by Mardaneus86** [comment]
Assigning would require me to give you permissions on this repository, as far as I can tell. You can just work on this and create a PR when ready.

**Comment by renard0** [comment]
Ok

**Comment by Mit010** [comment]
Would it also be possible to mass search min bin for a list of players you are on in your club? This would be useful because alot of the bronze players/silver players only get a update once like every twelve hours in futbin.

**Comment by Mardaneus86** [comment]
It's possible to search for multiple players, but it would take a long time since each player has to be searched individually. Especially if we want to take precautions to keep it similar to human behaviour.

**Comment by Mardaneus86** [comment]
Might be considered as automation as well. Won't implement.
