### ISSUE TITLE
Show FUTBIN BIN on the SBC squad

### ISSUE THREAD

**Issue by andytaihl** [Mardaneus86/futwebapp-tampermonkey#144]
It'd be a great feature to show the FUTBIN bin on every player and total squad price on the SBC squad. (maybe not only for SBC, also useful for our existing squad)
We might know that how much it costs and which player is more expensive. Is this possible?

![sbc 1](https://user-images.githubusercontent.com/43529612/47332692-a83ea280-d6b2-11e8-8cbc-7caa8fd0939f.jpg)

**Comment by Mardaneus86** [comment]
Implemented a simple solution for SBC and Squad screens with commit 6fb3782cedcdfd2ecb10daed4b89ed5d13d7c6f7 on the develop branch. Will be available after sufficient testing in the next release. Feel free to test on the `develop` branch if you want and let me know if you find any issues.

Only the Futbin values for the active squad members are calculated. Work area, subs and reserves are not counted.

<img width="1015" alt="sbc" src="https://user-images.githubusercontent.com/7780108/54152962-bb25f980-443e-11e9-85f4-cc02e0a931ac.png">

**Comment by irpan730** [comment]
hi Man :
    thank you for everything to do thoese things. it is a great convenient
for us to do the sbc .and can u send me the next release to test first .I
cant wait to use the total sbc price value function .thankyou.

Tim Klingeleers <notifications@github.com> 于2019年3月11日周一 下午12:50写道：

**Comment by Mardaneus86** [comment]
Just released on [v1.5.0](https://github.com/Mardaneus86/futwebapp-tampermonkey/releases/tag/1.5.0).

**Comment by irpan730** [comment]
Thx. If u come to China, just let me know . U have a lot fans (a lot means
dozens hahah.  we have a fifa channel all use ur script.)in here . I will
invite u to diner hahahaah.

Tim Klingeleers <notifications@github.com>于2019年3月15日 周五上午1:30写道：
