### ISSUE TITLE
Request: filter lists to rare

### ISSUE THREAD

**Issue by debugman5** [Mardaneus86/futwebapp-tampermonkey#152]
It would be nice to have the option to filter transfer results to only rare (or other options maybe)

I done something like that last year, but it was when there were multiple scripts, and I'm not
sure it will work in this year web app.

**Comment by Mardaneus86** [comment]
I think this can be merged with #119, which is an overall issue to collect stuff to filter on and how it should work with all those potential options without becoming confusing.

**Comment by ya-pop** [comment]
I made a simple script and added it to the bookmarks to filter the rare cards
`javascript:(function(){ $( "li.listFUTItem" ).hide(); $( "li.listFUTItem" ).each(function( index ) { if($( this ).find('.entityContainer .player').hasClass('rare')){ $( this ).show(); } }); })();`
