### ISSUE TITLE
Wrong BIN shown for Icons when pressing Check Minimum bin

### ISSUE THREAD

**Issue by guiseppeshen** [Mardaneus86/futwebapp-tampermonkey#154]
### Expected behavior:
Press search minimum bin - it is found and displayed in the right hand side of the menu.

### Current behavior:
It is consistently giving the wrong value when searching icons.  

### Metadata:
1.4.1 Chrome, Windows
![123](https://user-images.githubusercontent.com/33103785/49887520-7a651700-fe34-11e8-86ef-a317634a1438.JPG)

**Comment by guiseppeshen** [comment]
Cleared Transfer targets and it seemed to reset everything and works ok now.  maybe!

**Comment by Mardaneus86** [comment]
Remember it doesn't show the absolute minimum but an average of the lowest X cards. This is to prevent extreme outliers from skewing the result.
