### ISSUE TITLE
Fitness and contracts not correct

### ISSUE THREAD

**Issue by Regaddi** [Mardaneus86/futwebapp-tampermonkey#155]
### Expected behavior:
Fitness and contract count matches actual fitness and contract count.

### Current behavior:
Fitness is always at 99 and contact at 7.

### Metadata:
- **Script version:** 1.4.1
- **Browser:** Chrome 71.0.3578.98
- **OS:** Mac OS 10.13.6

![image](https://user-images.githubusercontent.com/1336590/50043976-737d1500-007d-11e9-8f68-b8437c04e354.png)

**Comment by Mardaneus86** [comment]
What screen is this behaviour noticed on? I just checked and I see all cards with the exact contracts and fitness in the Transfer Search and Club on my end.

By the way, the last card in your screenshot has a contract value of 1 instead of 7 😉

**Comment by Mardaneus86** [comment]
Closing because there is no feedback. Please reopen if needed.
