### ISSUE TITLE
transfer market crash

### ISSUE THREAD

**Issue by ya-pop** [Mardaneus86/futwebapp-tampermonkey#157]
READ BEFORE YOU ADD AN ISSUE: Do not request autobuyer features, because they are considered as cheating. Issues regarding autobuyers will be closed immediately.

### Expected behavior:
transfer market search should work 

### Current behavior:
transfer market search dosn't work 

### Metadata:
- **Script version:*1.4.1*
- **Browser:*chrome*
- **OS:*windows 10*

**Comment by Mardaneus86** [comment]
Please provide console or error messages if there are any. It's working as expected on my end.

**Comment by Mardaneus86** [comment]
Since there was no feedback I'm closing the issue. Please reopen if needed.
