### ISSUE TITLE
FutBin prices not being shown - new update to app?

### ISSUE THREAD

**Issue by guiseppeshen** [Mardaneus86/futwebapp-tampermonkey#162]
### Expected behavior:
The app should display the FutBIN BIN price in the transfer list and the my club page but it is only working in the transfer search page.  

### Metadata:
- **Script version:**1.4.1
- **Browser:** Chrome
- **OS:** Windows

**Comment by omasseau** [comment]
Same problem here.

**Comment by Mardaneus86** [comment]
Confirmed on the Transfer List page, however Futbin BIN price is shown in the club. Will investigate further.

Can you check for any error messages in the console?

**Comment by Mardaneus86** [comment]
v1.4.2 has been released, which fixes this issue.

**Comment by guiseppeshen** [comment]
thanks man

**Comment by guiseppeshen** [comment]
The green bar thing for bargains works great now, pretty cool feature :)

**Comment by omasseau** [comment]
It seems to be broken again since this evening (even after updating to 1.4.2)
