### ISSUE TITLE
Futbin Integration: not working on Transfer List

### ISSUE THREAD

**Issue by danielanguita** [Mardaneus86/futwebapp-tampermonkey#164]
### Expected behavior:
When you go to Transfer List, you see las prices from Futbin in the "Available Items".

### Current behavior:
It seems that since last Tampermonkey update, when you go to Transfer List, prices from Futbin will not load in the "Available Items", showing empty prices all over (or "--").

### Metadata:
- **Script version:** 1.41
- **Browser:** Chrome
- **OS:** Mac OSX

**Comment by Mardaneus86** [comment]
Update to [v1.4.2](
https://github.com/Mardaneus86/futwebapp-tampermonkey/releases/tag/1.4.2).
An issue with futbin has been fixed yesterday. See #162 

Can you let me know if that fixes it?

**Comment by danielanguita** [comment]
Updated to 1.4.2 and the issues is fixed. Working as expected now, thanks!
