### ISSUE TITLE
Futbin error

### ISSUE THREAD

**Issue by nokai** [Mardaneus86/futwebapp-tampermonkey#166]
Futbin say

Oops, there was an error - 403. Your client does not have permission to access this page at this time. Please try again at in a few minutes.

Get prices

**Comment by Mardaneus86** [comment]
Please use the issue template, the metadata section is there for a reason. Most likely you are still using v1.4.1. Make sure to upgrade to v1.4.2.

**Comment by JPriyank24** [comment]
Still happening with 1.5.2, got IP ban from futbin.
