### ISSUE TITLE
FUTBIN Prices not showing

### ISSUE THREAD

**Issue by guiseppeshen** [Mardaneus86/futwebapp-tampermonkey#168]
### Expected behavior:
FUTBIN price should be shown on transfer list & club player lists.

### Current behavior:
FutBin price not shown.  

Is this related to the bannings that happened? I was unaffected by that.  Has the feature been disabled or stopped somehow?

### Metadata:
- **Script version:** Tried 1.5, and 1.4.2
- **Browser:** Chrome
- **OS:**Windows

**Comment by guiseppeshen** [comment]
Also I should comment that Futbin still works from the same computer so I am not "banned" from futbin's main site.  it is just the fut enhancer app doesn't fetch prices and show them in the fut web app.

**Comment by ajpiano** [comment]
They changed the endpoint syntax slightly, however it is still possible to access the same data. You now need to send one `player` argument and can pass comma-separated `rids` for other ids you want to fetch. I assume this still has a max of 30, but haven't tested. Take a look at any futbin page now to see the new request params.

**Comment by castboom** [comment]
Same issue here. I know nothing about programming so can't help there but just noticed that FUTBIN prices aren't showing but I can still access their site.

**Comment by shikharg3** [comment]
Same issue here as well

**Comment by jpleon60** [comment]
Same issue.

**Comment by blackcalpac** [comment]
Same problem. Any improvement?

**Comment by omasseau** [comment]
Same problem here

**Comment by DeRutterQS** [comment]
Same here. Not banned and no prices shown anymore.

**Comment by danielanguita** [comment]
not working for me neither in Chrome OSX

**Comment by Mardaneus86** [comment]
I know the issue and I'm working on it. No need to all comment separately 👍

**Comment by Mardaneus86** [comment]
Just released an update (v1.5.2) that takes the updated Futbin url into account and also adds a 5 minute wait period in case a call to Futbin fails in order to prevent request spam. A notification will warn you when that happens.
