### ISSUE TITLE
update to v1.5.2, still not show price..

### ISSUE THREAD

**Issue by jjzhang10** [Mardaneus86/futwebapp-tampermonkey#169]
anyone has the similar issue?

I am using chrome.

**Comment by Mardaneus86** [comment]
You probably got an IP ban by Futbin for doing too many requests. They started enforcing stricter limits lately.

See #167.

**Comment by jjzhang10** [comment]
no. I did not get IP ban... I have tried several computers. but no one shows price.

**Comment by Mardaneus86** [comment]
Did you enable the Futbin integration setting again? Restarted the web-app after loading it? Do you get error messages in the browser console? Which platform?

**Comment by jjzhang10** [comment]
How to enable the futbin integration? I upload my setting in the attachment.
I have both xbox one and ps4, in both chrome and firefox. nothing works.
![futenchancer1](https://user-images.githubusercontent.com/11369834/54549826-e0ec5a80-4978-11e9-84db-f4756589ed54.png)
![futenchancer2](https://user-images.githubusercontent.com/11369834/54549827-e0ec5a80-4978-11e9-8473-5ef9b9d3d801.png)

**Comment by Mardaneus86** [comment]
You should see a gear icon in the bottom right in the web app. The options you want to enable for this script can be selected there.

**Comment by jjzhang10** [comment]
Great. It works. Thanks very much.
