### ISSUE TITLE
See club / transfer list worth based on minimum BIN

### ISSUE THREAD

**Issue by Kyderman** [Mardaneus86/futwebapp-tampermonkey#17]
Just an idea of an enhancement of some kind, would work well in conjunction with the minimized API call to futbin.

I've been working a little bit on this but not had real time to put forward yet.

Basically, it would be very handy to see the total futbin price of the club or transfer pile so we have a better understanding of what the club is worth, but also how the market is faring (possibly use localStorage to store previous values with times / dates so comparison can be made).

Additionally, being able to sort by highest futbin price would be a great addition.

**Comment by Mardaneus86** [comment]
That sounds like a very good feature to add. Feel free to share any source code you already have so we can expand on that.

**Comment by Kyderman** [comment]
@Mardaneus86 its very crappy and not achieving much atm, ill get something out when possible.

**Comment by Mardaneus86** [comment]
Made an initial version for the club worth. When you navigate to the club overview it shows club value on the top right.

Rest of the feature requests are not handled (yet):
- Show total Futbin value on transfer pile
- Market progress (not planning to implement soon since Futbin provides these charts)
- Sorting in club based on Futbin price

**Comment by Kyderman** [comment]
@Mardaneus86 
The club worth thing doesnt seem to be calculating correctly. I apparently have a club worth of a little over 19k although I have lots of players worth way more than that.

Glancing at the script I'm not massively sure what the problem is.

**Comment by Kyderman** [comment]
So doing some testing, only 91 players are being returned by the club.

91 x 200 is close to that 19000 figure with a few being worth more than the 200 BIN, so I'm assuming this is grabbing the 91 cheapest players in the club (which may be why your testing was correct (you had a small club)

**Comment by Kyderman** [comment]
Alright, so doing some digging, it seems like some sort of iterator needs to be called to get everything, as that collection as is, is not the "endOfList"

**Comment by Kyderman** [comment]
"MAX_ITEMS_REQUEST = 90" is something ive found in the code, is this changeable?

**Comment by Mardaneus86** [comment]
Oh you are right, I have a small club. I will check this evening and report back. Thanks for letting me know.

**Comment by Kyderman** [comment]
I have tried to trigger extra searches but cant find a function to make it happen unfortunately.
It loads 90, which is why you dont see another loading screen until the 3rd page of club players.

I guess a solution could be to make the bot go through all pages manually in a different tab to make a total up, would take a few minutes id imagine.

**Comment by Mardaneus86** [comment]
You can use the communication delegates (`communication.ClubSearchDelegate`) to change search criteria without screen interaction.
Do you get paging buttons when you have more than 90 players in your club? When I change the `MAX_ITEMS_REQUEST` constant to 10, I don't get paging.

You can't just change the `MAX_ITEMS_REQUEST` to 1000 for example, because that will return a 461 status code (Permission Denied). So some sort of paging will be necessary by using the `count` and `start` parameters on the `SearchDelegate`.

The question is how Futbin will handle that many items being requested. Probably the URL max length will be exceeded (since it is a `GET` request).

**Comment by Kyderman** [comment]
Ahh a search delegate!
I tell you what would be excellent, especially as you have had a longer look at this monstrosity than I. If you could make some wiki items for common functions, we could then add info to them over time. Otherwise myself or others or indeed yourself could spend a lot of time trying to find the correct functions.

I guess the best thing to do here is use the search delegate to do the 90 at a time, for maximum efficiency? we are looking at 2000 characters or so, so 90 players should be well within that limit.

**Comment by Mardaneus86** [comment]
Hm, that is a good idea to try to describe the web app architecture so everyone can benefit from that. 👍  As stated in the readme, this project is mainly for personal learning purposes, so this idea fits with that.

Also be aware that club size can easily get up to hundreds, so maybe requesting the total club value should be behind a user action (eg. clicking a specific button in the UI).

**Comment by Kyderman** [comment]
Yes for sure,

Have you got a quick way to call this searchDelegate? Im just trying to call it now to see if I can get  the required results.

**Comment by Mardaneus86** [comment]
Nope, you will need to figure out what parameters this delegate requires. What I can tell you right now on top of my head is that you should call it in this form:

```js
var o = new communication.ClubSearchDelegate(searchcriteria, start, count);
o.addListener(communication.BaseDelegate.SUCCESS, this, function marketSearch(sender, response) {
     // handle the response
}));
o.send();
```

The second and third parameter are the most important.

If you set a breakpoint in the Chrome developer tools in the Sources tab in the `compiled_1.js` file at the line after `communication.ClubSearchDelegate = function(t, i, s) {` you can inspect the objects that you have to pass.

PS: you can pretty print the code by pressing the curly braces in the sources tab.

**Comment by Kyderman** [comment]
Yeah, im just working out what needs to be in "t" atm, nearly got it sorted.

**Comment by Kyderman** [comment]
```
var o = new communication.ClubSearchDelegate({
    type: enums.SearchType.PLAYER, 
    sort: "desc",
    playStyle: 1, 
    defId: 1, 
    position: enums.SearchType.ANY, 
    year: enums.SearchType.ANY, 
    category: enums.SearchCategory.ANY,
    level: enums.SearchLevel.ANY, 
    club: 0, league: 0, nation: 0,
    isExactSearch: false, 
    zone: enums.SearchType.ANY  }, 0, 10);
o.addListener(communication.BaseDelegate.SUCCESS, this, function marketSearch(sender, response) {
     // handle the response
});
o.send();
```

Thus far, erroring at lack of function `t.hasValidDefId()`

**Comment by Mardaneus86** [comment]
Ah, create it with `var t = new transferobjects.SearchCriteria();`. That'll make sure the search criteria object is created properly.

I see there is need for some architectural documentation. Will work on that with priority.

**Comment by Kyderman** [comment]
Excellent, you are a diamond!

**Comment by Kyderman** [comment]
Any idea of defId and playStyleId etc?

**Comment by Kyderman** [comment]
```
var t = new transferobjects.SearchCriteria();
var o = new communication.ClubSearchDelegate(t, 0, 250);
o.addListener(communication.BaseDelegate.SUCCESS, this, function marketSearch(sender, response) {
     console.log(response)
});
o.send();
```

OK, so this will actually bring us back the first 250 players in the club, sorted by loans, then informs etc, then normal players. Excellent.

From here, its the following:

1. Filter to players only
2. filter untradeable
3. mapIds
4. chunk ids into manageable get string chunks for futbin
5. profit?

**Comment by Mardaneus86** [comment]
I created a Gitter IM channel to have a better way of discussing instead of polluting the issues. Please continue discussion there: https://gitter.im/futwebapp-tampermonkey

By the way; very good work 👍  Keep the count on 90, otherwise EA can figure out false requests pretty easily.

**Comment by Kyderman** [comment]
Good point, will leave this clearer for important breakthroughs and news :)

**Comment by Kyderman** [comment]
UPDATE:

I have this fully working with the first 90 players in the club, with untradeable players filtered.

I will have this feature completed this evening, atm it will run in the background, however, ill probably try get a UI button together for it

**Comment by Kyderman** [comment]
So new changes have been requested, it works a lot quicker.

A little suggestion I could work on.

I think the club value would be great in the top bar alongside fifa points etc, could use a button for refreshing it?

If so, any idea on the right screen stuff to call for that (it wouldnt just be in the player page)
