### ISSUE TITLE
Mobile usage

### ISSUE THREAD

**Issue by richardx95** [Mardaneus86/futwebapp-tampermonkey#173]
I've read an discussion about this subject last year. But that post wasn't supported massively and so you decided to not realise it.
I'm currently trading like 80% on my phone so I would love to see an addon for Android.

**Comment by Mardaneus86** [comment]
At the time I didn't look in depth at it, but without official Tampermonkey support for mobile, this is not something I can add. See https://openuserjs.org/about/Tampermonkey-for-Android, it states the following:
> WARNING!
>This is a pilot study and the version of Chrome that has this embedded Tampermonkey is out of date. Use at your own risk!

The reasons I mentioned back then still apply (see #87).
