### ISSUE TITLE
Remove autobuyer limit of a player name

### ISSUE THREAD

**Issue by gianemi2** [Mardaneus86/futwebapp-tampermonkey#18]
I think should be better for sniping to add the feature to just autobuy for price, or for league or for card color. 

Is it possible?

**Comment by Mardaneus86** [comment]
I've added this as a precaution feature by issue #15, so you can only snipe specific items.

You can change the script for yourself by removing a few lines: https://github.com/Mardaneus86/futwebapp-tampermonkey/blob/master/autobuyer.user.js#L88-L94

If you want you can add a PR where a user can override this check if he really wants.

Closing for now. Please reopen if you have additional questions or remarks.
