### ISSUE TITLE
[request] will it be possible to search for squad fitness ?

### ISSUE THREAD

**Issue by gauravbellani** [Mardaneus86/futwebapp-tampermonkey#180]
would love a feature that will allow us to search specifically for squad fitness. right now its possible to only search by fitness and that includes player fitness as well. 

### Describe the solution you'd like
just perhaps a checkbox that says "squad fitness only" after we choose "fitness" in the "consumables" part of the market

**Comment by Mardaneus86** [comment]
Fitness and fitness cards are no longer relevant in FIFA 21.
