### ISSUE TITLE
Search for minimum bin isn't working

### ISSUE THREAD

**Issue by mehrdadie** [Mardaneus86/futwebapp-tampermonkey#184]
Hey, Thanks for your really helpful script.
Search for the minimum bin isn't working and it stays at the searching stage.
Browser: Google Chrome

![Screenshot at Sep 20 00-37-37](https://user-images.githubusercontent.com/10621043/65277311-e18bc680-db3e-11e9-9c13-36cb3626daaa.png)

**Comment by Mardaneus86** [comment]
As you may have noticed not everything is working yet 😄 If anyone feels like helping out, it would be very much appreciated!

Will try to get a fix out asap.
