### ISSUE TITLE
'Instantly confirm Buy It Now dialog' doesn't work

### ISSUE THREAD

**Issue by mtn410** [Mardaneus86/futwebapp-tampermonkey#185]
Thank you for the script.
The 'Instantly confirm Buy It Now dialog' feature doesn't work in the FUT 20 web app. 
Browser: Google Chrome

**Comment by Mardaneus86** [comment]
As you may have noticed not everything is working yet 😄 If anyone feels like helping out, it would be very much appreciated!

Will try to get a fix out asap.

**Comment by mtn410** [comment]
> 
> 
> As you may have noticed not everything is working yet 😄 If anyone feels like helping out, it would be very much appreciated!
> 
> Will try to get a fix out asap.

FUTBIN Prices do! :)
Appreciate your efforts!
