### ISSUE TITLE
[Request] Store tradelists move in my website

### ISSUE THREAD

**Issue by Heirani** [Mardaneus86/futwebapp-tampermonkey#186]
First of all sorry for my english as I'm french.

I am the developper of a website dedicated to traders. Last year I added a functionnality where the members had to copy the "tradepile response" into a textarea in a form on my website. Everything was saved in a database where each member can have statistics and history of their trade moves.
I was wondering if it would be possible to add this to FutEnhancer.

I wish I can dm with you soon.
GREAT JOB!

**Comment by Mardaneus86** [comment]
Can you please be more clear on what you want to achieve?

You can use [Gitter](https://gitter.im/futwebapp-tampermonkey/Lobby) if you want to DM me.

PS: Don't add links to your website, Github isn't meant for marketing 😉

**Comment by Heirani** [comment]
"no link" Yes I was sure of it ;) I go dm you on Gitter. Thank you.

**Comment by Mardaneus86** [comment]
As discussed via DM, closing this for now.
