### ISSUE TITLE
Minimum Bin Shows wrong Prices

### ISSUE THREAD

**Issue by MoAshir** [Mardaneus86/futwebapp-tampermonkey#190]
minimum bin shows wrong prices after searhing them multiple times in Fifa 20

**Comment by Mardaneus86** [comment]
Too little info to do something about it. Working fine on normal gold, silver and bronze here...

Closing because I need more detail. Feel free to reopen after you add more detailed information about what is wrong and what is expected.

**Comment by MoAshir** [comment]
For Example current price of Muller : 12000
using minimum bin it show more than 12000 . is it becoz i use 1 item to determine the price ?
