### ISSUE TITLE
Auto click the buy now button along with confirm

### ISSUE THREAD

**Issue by AaronClifford** [Mardaneus86/futwebapp-tampermonkey#196]
I can't for the life of me find out how to add this! Would be useful for sniping

**Comment by Mardaneus86** [comment]
I'm not considering to add functionality to aid in automatic buying since that opens the door to using this for bot purposes.

I understand you would find this useful, but it's a grey area which I do not want to participate in. Feel free to reopen if I misunderstood what you are trying to achieve.
