### ISSUE TITLE
Search for minimum bin not working. 

### ISSUE THREAD

**Issue by furkick** [Mardaneus86/futwebapp-tampermonkey#204]
READ BEFORE YOU ADD AN ISSUE: Do not request autobuyer features, because they are considered as cheating. Issues regarding autobuyers will be closed immediately.

### Expected behavior:
Click on search minimum BIN, returns minimum BIN

### Current behavior:
Click on search minimum BIN, hangs at searching minimum BIN....
### Metadata:
- **Script version:** 1.6.2
- **Browser:** Chrome Version 78.0.3904.97 (Official Build) (64-bit)
- **OS:** Windows 10 64-bit

### To Reproduce
1. Go to transfers page.
2. Click on any player.
3. Click search minimum BIN button.
4. See error.

### Screenshots
![Capture](https://user-images.githubusercontent.com/7430414/69063438-66e30880-0a14-11ea-842f-3d15e2a0cab0.PNG)

### Error:
_**transferobjects is not defined.**_
`
    const searchCriteria = new transferobjects.SearchCriteria();
`

**Comment by Mardaneus86** [comment]
If anyone can create a PR for this, please do! I have no time to work on this right now unfortunately.

**Comment by furkick** [comment]
Hi, So I've been digging and seems the following 'fixes' the issue. Point to note I am not a great JS dev so not sure if this is correct or will result in any issues with the build. Please check and let me know if you want me to do a PR on the dev branch?

Replace:

`const searchCriteria = new transferobjects.SearchCriteria()`

With:

```
// eslint-disable-next-line no-undef 
const searchCriteria = new UTSearchCriteriaDTO();
```

**Comment by furkick** [comment]
> Hi, So I've been digging and seems the following queries the transfer list, but there is an issue when selecting a player after doing it the first time, seems the BIN price does not return correctly from the second time onwards.
> 
> Replace:
> 
> `const searchCriteria = new transferobjects.SearchCriteria()`
> 
> With:
> 
> ```
> // eslint-disable-next-line no-undef 
> const searchCriteria = new UTSearchCriteriaDTO();
> ```

**Comment by CasperSchjoett** [comment]
I'm not even able to query any player BINS at all, so i find it weird that you're actually able to query the first you choose.

**Comment by furkick** [comment]
> I'm not even able to query any player BINS at all, so i find it weird that you're actually able to query the first you choose.

**Comment by furkick** [comment]
The line of code modified shown in my post did query the first attempt successfully but had unusual behaviour after that. I haven't had time to look at this any further. If you replace the line shown and rebuilt the app then you should get the same results.

**Comment by guiseppeshen** [comment]
"Although if you wait say a minute+ then it randomly works sometimes. "

You can force it to 'redo' the second search properly by pressing compare price first and then pressing search minimum bin.  Almost as if that "clears the cache".  

Maybe that can help you to understand the problem.

**Comment by CasperSchjoett** [comment]
> The line of code modified shown in my post did query the first attempt successfully but had unusual behaviour after that. I haven't had time to look at this any further. If you replace the line shown and rebuilt the app then you should get the same results.

I'm not familiar with JavaScript so i have no idea where and how to change the variable, sadly.

**Comment by furkick** [comment]
So it seems the problem lies somewhere in the following:

`services.Item.searchTransferMarket`

When searching for a player after successfully getting a BIN the first time (as described before) the function seems to return information based on the first player searched for, not the second. I have hacked about at it and can get it to work if you put in a large delay 10 seconds+ in the `async _findLowDown` function.

As @guiseppeshen  mentioned it seems there may be a cache of some sort and after adding a large delay this seems to clear.

**Comment by furkick** [comment]
@Mardaneus86 Spot on with the cache, I have tested with multiple use cases and seems to be fixed now. PR: https://github.com/Mardaneus86/futwebapp-tampermonkey/pull/205
