### ISSUE TITLE
Club Search BIN Prices

### ISSUE THREAD

**Issue by Kyderman** [Mardaneus86/futwebapp-tampermonkey#21]
I'm not seemingly able to get prices when I search the club, e.g searching bronze players, I get no prices

Additonally, the informs in my club are not giving the correct price, those on the trade pile do.

**Comment by Mardaneus86** [comment]
I have no IF's in my club to test, but there are some issues with the price matching for IF's in the other screens as well. There are some issues with the current approach when switching screens. Have a fix ready in a moment.

**Comment by Mardaneus86** [comment]
Closing the issue for now, reopen if the problem still exists.

**Comment by Kyderman** [comment]
Is it worth us getting a test club together? Is it feasible? Would take a bit of time investment to build it up to have "1 of everything" though.
