### ISSUE TITLE
Lack of updates

### ISSUE THREAD

**Issue by gauravbellani** [Mardaneus86/futwebapp-tampermonkey#217]
that there has been no new features for a very very long time. existing features like fetch futbin prices do not work as well. I had made a donation/contribution out of my savings when the dev made it all so quickly available for fifa 20, but its just been dead for months.

**Comment by Mardaneus86** [comment]
I'm very sorry to hear that you are disappointed. I initially started this project for learning purposes and it grew to become what it is now, completely free of charge. I appreciate the donation you made. Other personal projects occupied me for quite a while, and I'm not even playing the game anymore.

As much as I would like to continue with adding features to this project, I feel like I can't keep up the effort on my own without a proper business model in place. I will update the readme soon to make sure this is known for all users. 
Futbin's change caused quite some issues for a lot of users. So as long as there is no proper API to get player prices, that will remain a problem.

If anyone wants to sign up as a maintainer of the project, who has the same core values as I have (eg. not help cheating in any way), I'm all ears.
