### ISSUE TITLE
FUT 21

### ISSUE THREAD

**Issue by StreicK** [Mardaneus86/futwebapp-tampermonkey#223]
Can you update for new web app for FIFA 21? Thanks! Was great last year

**Comment by guiseppeshen** [comment]
I second this motion

**Comment by Baaasta** [comment]
Yes please. Best feature is the Futbin price indicator.
pls help us

**Comment by veredic** [comment]
+1, just need an update to make script work inside FUT21, the rest I can try to change myself =)

**Comment by chegerg** [comment]
Ea has changed the code of the object UTobservable is not recognize. I search an issue. 
The error is windows.UTobservable.

**Comment by totti240282** [comment]
UTobservable is js object ?

**Comment by eimarfandino** [comment]
try EAObservable @chegerg

**Comment by totti240282** [comment]
I would like to learn how to use the web app objects can you help me?

**Comment by chegerg** [comment]
@eimarfandino thx i try.
All the name are changed ?

**Comment by eimarfandino** [comment]
@chegerg  not only EAObservabe changed, also the screenIds are all different

**Comment by eimarfandino** [comment]
i have until now the transferlis/ playerlist working. SBC and Squat price still not working

**Comment by chegerg** [comment]
ok  Extra card information ok, instant buying ok, Futbin price ?

**Comment by eimarfandino** [comment]
> > i have until now the transferlis/ playerlist working. SBC and Squat price still not working
> 
> ok Extra card information ok, instant buying ok, Futbin price ?


Extra card information ok, yes working
futbin price: yes working
instant buying: yes working

**Comment by chegerg** [comment]
> Extra card information ok, yes working
> futbin price: yes working
> instant buying: yes working

Futbin price and berghain not working for me ???

**Comment by chegerg** [comment]
@eimarfandino 
Do you change something for berghain and futbin price ?

**Comment by eimarfandino** [comment]
i have change many things yeah, i manage to get the SBC and Squat now working

**Comment by chegerg** [comment]
Can you upload your code please ? For sharing with the others I just want futbin price and berghain

**Comment by chegerg** [comment]
@eimarfandino 
Can you upload your code please ? For sharing with the others I just want futbin price and berghain.

**Comment by Mardaneus86** [comment]
I wasn't planning to buy the game this year so it's quite difficult for me to help you guys out. Time is very limited lately so I have to give priority to paid projects.

Feel free to do a PR, and if someone wants to become a maintainer or provide me with some way to get access to the web app I can do a best effort job of helping everyone out to get at least the basics working again.

**Comment by eimarfandino** [comment]
I can maintain it in y free time, I think i almost got it working for fifa 21. Are there any fifa rewards for maintaining this? :-)

**Comment by Mugunaz** [comment]
I'm happy to pay something if you get it working

**Comment by Mardaneus86** [comment]
Haha nope. Apart from the few donations there is no earnings in this. That's why I have to make a choice between paid projects and voluntary work. You can understand where my priorities go.

**Comment by eimarfandino** [comment]
totally understand you @Mardaneus86.

**Comment by chegerg** [comment]
ok Mardaneus thx i search too for berghain and futbin price. @eimarfandino what have you change for futbin and berghain please ?

**Comment by Mugunaz** [comment]
Yes I totally understand @Mardaneus86

**Comment by jhuriez** [comment]
Hi @Mardaneus86 , I am interested in adapting the project for FIFA 21, but some things are blocking me in the development: 

- When I open the Developer Web Tools on Chrome (F12), the page gets stuck because of the debugger.
- Unable to do "console.log()", EA code overloaded the "console" object

Do you have solutions against these blockages that EA has implemented?

**Comment by eimarfandino** [comment]
ok, so all works except buy packs..... some constants also changed on EA side

**Comment by chegerg** [comment]
> ok, so all works except buy packs..... some constants also changed on EA side

Nice what did you expect by buy pack ?

**Comment by eimarfandino** [comment]
@chegerg normally i don't buy packs, but the idea is that the script does not brake the normal functionality of the site, trying now to remove the autoconfirm from the pack buys

**Comment by chegerg** [comment]
> @chegerg normally i don't buy packs, but the idea is that the script does not brake the normal functionality of the site, trying now to remove the autoconfirm from the pack buys

Ah ok i understand, yes this is a security in fact.

**Comment by chegerg** [comment]
Isearch for futbin integration and berghain...... i'm a beginner ;)

**Comment by veredic** [comment]
@eimarfandino can you share your code? or do a PR ?

**Comment by eimarfandino** [comment]
Sure, give me some time to put it there, got distracted with some other things

**Comment by veredic** [comment]
@eimarfandino thank you  =)

**Comment by eimarfandino** [comment]
> Hi @Mardaneus86 , I am interested in adapting the project for FIFA 21, but some things are blocking me in the development:
> 
> * When I open the Developer Web Tools on Chrome (F12), the page gets stuck because of the debugger.
> * Unable to do "console.log()", EA code overloaded the "console" object
> 
> Do you have solutions against these blockages that EA has implemented?

Hi @jhuriez,

for point 1, you'll need to blackbox the blocking script in the devtools.

**Comment by warmshower** [comment]
made an account just to say thank you guys for working on this, loved this app last year

**Comment by totti240282** [comment]
> > Hi @Mardaneus86 , I am interested in adapting the project for FIFA 21, but some things are blocking me in the development:
> > 
> > * When I open the Developer Web Tools on Chrome (F12), the page gets stuck because of the debugger.
> > * Unable to do "console.log()", EA code overloaded the "console" object
> > 
> > Do you have solutions against these blockages that EA has implemented?
> 
> Hi @jhuriez,
> 
> for point 1, you'll need to blackbox the blocking script in the devtools.

Example?

**Comment by eimarfandino** [comment]
> > > Hi @Mardaneus86 , I am interested in adapting the project for FIFA 21, but some things are blocking me in the development:
> > > 
> > > * When I open the Developer Web Tools on Chrome (F12), the page gets stuck because of the debugger.
> > > * Unable to do "console.log()", EA code overloaded the "console" object
> > > 
> > > Do you have solutions against these blockages that EA has implemented?
> > 
> > 
> > Hi @jhuriez,
> > for point 1, you'll need to blackbox the blocking script in the devtools.
> 
> Example?

https://developer.chrome.com/devtools/docs/blackboxing

**Comment by eimarfandino** [comment]
i have the packs working, i'll put all tomorrow in a branch and send the Pull requests.

**Comment by Vivalemuc** [comment]
I cant wait :P 
Can you juste post the script in a gist ? ;)

**Comment by eimarfandino** [comment]
https://gist.github.com/eimarfandino/f5c010d37ad30815a3a2bdf2e5cd59fe.js

**Comment by Vivalemuc** [comment]
I cant see the code :(

**Comment by eimarfandino** [comment]
please try again: https://gist.githubusercontent.com/eimarfandino/f5c010d37ad30815a3a2bdf2e5cd59fe/raw/524057183b260f5b89eeb0bc29e458205e4d1c75/gistfile1.txt

**Comment by veredic** [comment]
is it right in the last link?

**Comment by Vivalemuc** [comment]
Perfect :)

**Comment by eimarfandino** [comment]
yes it is, guys dont forget to donate :-) was some effort. https://www.paypal.com/paypalme/eimarfandino

**Comment by eimarfandino** [comment]
I'll be officially releasing it in the following days

**Comment by veredic** [comment]
error in tampermonkey here, maybe because its all in 1 line (line 20)

**Comment by veredic** [comment]
thank you, will donate soon =) thanks for your work

**Comment by eimarfandino** [comment]
@veredic does it work now for you?

**Comment by veredic** [comment]
still no, I copy and paste your git to tampermonkey new script but doesnt work

**Comment by Vivalemuc** [comment]
ReferenceError: _0x1a026c is not defined

Error when you display console :/

**Comment by eimarfandino** [comment]
yes, that was already there:
// prevent debugger trap
setInterval(() => {
  _0x1a026c = function () {}; // eslint-disable-line no-global-assign, no-undef
}, 500);

**Comment by Mardaneus86** [comment]
Keep the slowchat to a minimum please. There is a gitter chat for that.

Also I'd like to warn for installing scripts that can't be validated with actual code from a PR. So be careful by just installing from these gists.
As much as I appreciate the work, this isn't the place to request for donations. I'd be happy to add a link once we have this working for everyone.

**Comment by veredic** [comment]
It is working, btw the code is pretty modified from the last 3 years - present, will wait a PR too

**Comment by eimarfandino** [comment]
thanks @Mardaneus86, agree with you. I just wanted to share the file with @veredic and @Vivalemuc that were waiting for it. I have removed the gist. I'll proceed the following days with a pull request and make it public via an official release

**Comment by Vivalemuc** [comment]
The scripts work but can you try to modify the display on transfert list ? Increase width to dispay all data correctly ;)

**Comment by Mardaneus86** [comment]
Locking the conversation until there is a PR. I'll make sure the release will follow soon after the PR has been approved.

The work is very much appreciated by the community.

PS: open new issues for new feature requests

**Comment by Mardaneus86** [comment]
[v2.0.0 has been released](https://github.com/Mardaneus86/futwebapp-tampermonkey/releases/tag/2.0.0) with an update for FIFA 21!

Huge thanks to @eimarfandino for his work on this!
