### ISSUE TITLE
Increase width of columns in transfert list page

### ISSUE THREAD

**Issue by Vivalemuc** [Mardaneus86/futwebapp-tampermonkey#224]
Increase div size to show all FUTBIN data!

At the moment, the data is slightly truncated. Allow to expand the div to display everything, there is space on the left side;)

**Comment by eimarfandino** [comment]
sure, once the release for F21 is done we can take a look to this

**Comment by Vivalemuc** [comment]
`.listFUTItem .auction{
display: flex;
    flex-direction: row;
    flex-wrap: wrap;
    max-width: 30rem;
    position: absolute;
    top: 30%;
    width: 50%;
}`

It will be better, but can you modify CSS comportment ?
