### ISSUE TITLE
Refresh transfer list no fonctionning ?

### ISSUE THREAD

**Issue by chegerg** [Mardaneus86/futwebapp-tampermonkey#229]
READ BEFORE YOU ADD AN ISSUE: Do not request autobuyer features, because they are considered as cheating. Issues regarding autobuyers will be closed immediately.

### Expected behavior:
Transfert refresh 

### Current behavior:
An error occured when refresh transfert List

### Metadata:
Last version script
Chrome
Windows 10

### To Reproduce
Click on button refresh transfert.

**Comment by eimarfandino** [comment]
i see, ok, let me work on a fix for this. thanks for reporting it

**Comment by eimarfandino** [comment]
what does this function exactly does?

**Comment by Mardaneus86** [comment]
It should refresh the transferlist on the same page, without having to go back to the search page again. Seems like there is a `NaN` instead of the current page for the `start` parameter. Will take a look tonight.

**Comment by chegerg** [comment]
thx a lot.

**Comment by eimarfandino** [comment]
@Mardaneus86 , will you work on a fix for this issue or need a hand?

**Comment by Mardaneus86** [comment]
It is fixed in the develop branch already, just bundling a bit before merging to master to prevent a lot of bugfix releases in a short time.

**Comment by chegerg** [comment]
Hello The bug is fixed ?
Thx a lot for your great work

**Comment by Feigenstaub** [comment]
Updated to the new version 2.01, went into the 59th. minute and keep pressing refresh list.
It seem to refresh the page, but not a single listing is updated? Items bought are still there and no new listings appear.
What is that option for? I do not see any use of it or it is still bugged.

**Comment by Mardaneus86** [comment]
The web app caches requests for some time, so it might take some time before you see new results. Needs some investigation to see if this cache can be circumvented somehow and if it's safe to do so.
