### ISSUE TITLE
Object services 

### ISSUE THREAD

**Issue by totti240282** [Mardaneus86/futwebapp-tampermonkey#236]
I have a curiosity because using the services object of the webapp I get encrypted results?

**Comment by Mardaneus86** [comment]
Can you show us a screenshot or something? Does it also happen if you disable the Tampermonkey script?

**Comment by totti240282** [comment]
if I use the command from the console the result is encrypted with your script no

**Comment by Mardaneus86** [comment]
Which command do you execute from the console? Please be more clear, or better yet show a screenshot.

**Comment by totti240282** [comment]
Example:

 var searchCriteria = getAppMain().getRootViewController().getPresentedViewController().getCurrentViewController().getCurrentController()._viewmodel.searchCriteria;
 
        searchCriteria.maxBid =10000000; 
        services.Item.clearTransferMarketCache();

        services.Item.searchTransferMarket(searchCriteria, 1)

**Comment by Mardaneus86** [comment]
Well that's because `services.Item.searchTransferMarket` returns an observable. However this isn't actually an issue but more help with coding, I'll have to refer to Gitter. These issues are meant for bugs or feature requests.

**Comment by totti240282** [comment]
ok sorry,
where can I post these question ?
