### ISSUE TITLE
Prices no longer showing on club players page

### ISSUE THREAD

**Issue by hmust92** [Mardaneus86/futwebapp-tampermonkey#238]
I was listing players for transfer on the club players page and the prices were showing just fine, until they suddenly stopped showing. I've tried reinstalling the plugin, clearing application state and refreshing and turning the setting on an off but it doesn't work.

### Expected behavior:
Player prices from FUTBIN show render for each player in the club players page.

### Current behavior:
Player prices from  FUTBIN no longer render for the player in the club players page.

### Metadata:
- **Script version:** : 2.0.2
- **Browser:**: Chrome
- **OS:**: macOS Catalina
Here's a snapshot of the console. Could this be an issue with FUTBIN's API?
<img width="1440" alt="Screen Shot 2020-10-10 at 7 34 15 PM" src="https://user-images.githubusercontent.com/35225030/95667734-ad12f000-0b2f-11eb-870c-fecb6ff30fe7.png">

### To Reproduce
1. Go to Club, 
2. Click on Players
3. Look at players

### Screenshots
What I am seeing:
<img width="1440" alt="Screen Shot 2020-10-10 at 7 31 15 PM" src="https://user-images.githubusercontent.com/35225030/95667708-3b3aa680-0b2f-11eb-99ba-3483ebd28c5a.png">
My settings:
<img width="1357" alt="Screen Shot 2020-10-10 at 7 30 54 PM" src="https://user-images.githubusercontent.com/35225030/95667710-4097f100-0b2f-11eb-8edd-4a1113228972.png">

**Comment by Mardaneus86** [comment]
You've done too many requests to futbin, that's what the message says. Related to #199 

This should have been fixed in v2.0.2 for the most part, unless you do a huge amount of page views. Will probably add an option later to request futbin updates manually instead of automatically. Will bundle all communication in the other issue.
