### ISSUE TITLE
Auto-buyer removed?

### ISSUE THREAD

**Issue by just4u32** [Mardaneus86/futwebapp-tampermonkey#24]
Hi there,

Why was auto buyer removed? Are we expecting a new version?
Using the old one, with the improvement suggested in the PR, I got some nice hits yesterday, but none since (a few hours running, with smaller delay - 3-5 seconds each).

Is it broken?

Thanks for all your efforts.
Is there any place we can chat?

**Comment by just4u32** [comment]
Here is a part of the log:

**Comment by Mardaneus86** [comment]
It has been moved to a separate branch because, after some thought, an autobuyer isn't the main purpose I wanted to pursue with this project. I just wanted to show how easy it is to create, so EA can fix it for the future, so the game is more enjoyable for everyone.
The goal of the project is to enhance the FUT web app experience to make it more enjoyable and user friendly.

Chatting is possible with the gitter button on the readme.

**Comment by debugman5** [comment]
The link to install the script is down

**Comment by Mardaneus86** [comment]
That's correct. You can still test the code by viewing the raw file here on github.

I've removed the script from Openuserjs.com for the same reason as stated above.

**Comment by randomsecguy** [comment]
Hi Mardaneus86,

Where can I find this raw file that you mentioned? Thank you

**Comment by Mardaneus86** [comment]
Check the branch list ;-) It's fairly obvious. Remember that you might get banned fairly easily by using it.

**Comment by randomsecguy** [comment]
@Mardaneus86 Thanks. I get that. Just had an idea and wanted to look at how you were doing things :)

What about other features of the scripts...has anybody reported being banned for using futbin prices script or so?

**Comment by Mardaneus86** [comment]
No mentions of it yet. I'm incorporating pinEvents for most scripts as well. Will be finished with that soon; so there is no way to tell if it's automated or not.

**Comment by randomsecguy** [comment]
That would be great. Looking forward to further updates :+1:

**Comment by LucaNardini** [comment]
@Mardaneus86 Good job here, this is exactly what I was looking for. A question: I was trying to find the raw file of the Autobuyer script, but I can't find it even in the related branch. Is it just me or it has been removed?

**Comment by Mardaneus86** [comment]
It wasn't you, it's available again :-) made a merge mistake
