### ISSUE TITLE
Show futbin price on the pack opening page

### ISSUE THREAD

**Issue by debugman5** [Mardaneus86/futwebapp-tampermonkey#25]
headline

**Comment by Mardaneus86** [comment]
Currently unable to test, I need to access the game on the console before I get access to the FUT Web App transfer market again, but I didn't buy the game (yet). If someone can provide me with a test account I'm happy to look at this.

**Comment by Kyderman** [comment]
+1

There are also a few places that need the futbin price for players to re render. Maybe need to look at some sort of caching.

**Comment by debugman5** [comment]
And it would be nice also on search players results page
