### ISSUE TITLE
Stopped working

### ISSUE THREAD

**Issue by Roshinante59** [Mardaneus86/futwebapp-tampermonkey#252]
Hello, the script doesn't work anymore since like 2 hours it gives this message in the browser console 
![image](https://user-images.githubusercontent.com/72010727/100793040-dc512980-341b-11eb-9ab3-a501ea0bef94.png)

**Comment by Boublond** [comment]
Hello, Yes I have the same bug actually. I don't know what happened.

**Comment by FuJisPT** [comment]
All scripts FUT WEB stop worked...

**Comment by cnbrkc** [comment]
Same error. Please update :)

**Comment by Mardaneus86** [comment]
EA has renamed some variables. Not sure how intrusive their changes will be. Don't have an account to try it out, so I reached out on Gitter to get access to one

`services.Authentication._oAuthentication` has been renamed to `services.Authentication.oAuthentication` for example..

**Comment by horotec** [comment]
thanks..hope to get an update soon!

**Comment by robertinho77** [comment]
It's only the oAuthentication variable. If you renamed it to services.Authentication.oAuthentication your script is working again

**Comment by Mardaneus86** [comment]
Had to add a delay as well around the authentication check, since the service is no longer added immediately. Build is running so update should be available soon!

**Comment by Boublond** [comment]
I updated the script on my side but it doesn't work. Are you sure that it's the only update that we need to do ?

**Comment by Mardaneus86** [comment]
Travis seems to be exceptionally slow today. Taking way longer than expected.

By the way: please be more specific than "it doesn't work". What did you update/test/see?

**Comment by Boublond** [comment]
Hi, 
I changed the following line : " services.Authentication._oAuthentication.observe(undefined, function () {" by : "services.Authentication.oAuthentication.observe(undefined, function () {" 
I always have the same error : "ERROR: Execution of script 'FUT Enhancer' failed! Cannot read property 'oAuthentication' of undefined". 

I also tried to replaced enums.PIN.EVENT.PAGE_VIEW by PINEventType.PAGE_VIEW
But the result is always the same. 

Thanks in advance.

**Comment by Mardaneus86** [comment]
Take a look at the referenced commit instead: https://github.com/Mardaneus86/futwebapp-tampermonkey/commit/aa964de5b589a1842a8f1c4981390a7f189c19fa The timeout is important (might be better solutions but this works right now). Will be available soon as an update if Travis wants to work.

**Comment by Boublond** [comment]
Thanks a lot it works perfectly now !

**Comment by cnbrkc** [comment]
I still can't run it. I don't really understand this code work and I think https://openuserjs.org/install/Mardaneus86/FUT_Enhancer.user.js is not updated.
When can you update? I still can't run :(

**Comment by Mardaneus86** [comment]
Build finally completed, updated the script on openuserjs as well. Release [2.0.3](https://github.com/Mardaneus86/futwebapp-tampermonkey/releases/tag/2.0.3) is available. Everything before this version will no longer work because of the changes EA made.

**Comment by artvidal91** [comment]
how do i update  2.0.3?
