### ISSUE TITLE
Mobile phone + Kiwi

### ISSUE THREAD

**Issue by chegerg** [Mardaneus86/futwebapp-tampermonkey#253]
Hello,

Would it be possible to run the application on a phone with kiwi (Android). I have a message saying:
Rotate Device.
I saw in the script:
 // force full web app layout in any case
    $ ('body'). removeClass ('phone'). addClass ('landscape');

    _core.Queue.getInstance (). start ();

Should we change something?

Thx a lot

**Comment by Mardaneus86** [comment]
Phone usage is not supported with this script. No plans to do so either, sorry.

**Comment by chegerg** [comment]
We can use tampermonkey with Kiwi navigator and your script i test but i have a message saying : Rotate device

**Comment by Mardaneus86** [comment]
I know, but the script is not optimized nor tested for mobile. Therefore the `phone` class is removed.

**Comment by chegerg** [comment]
ok thx a lot

**Comment by chegerg** [comment]
Do you have an idea of ​​the changes to be made in your script ?
