### ISSUE TITLE
Search Minimum not work with new version?

### ISSUE THREAD

**Issue by cnbrkc** [Mardaneus86/futwebapp-tampermonkey#254]
Search Minimum bin not working for me only? Other things are working. But the lowest price is not looking.

**Comment by cnbrkc** [comment]
```
Uncaught TypeError: Cannot read property 'EVENT' of undefined
    at Window.eval (userscript.html?name=FUT%20Enhancer.user.js&id=e7199822-09ce-48b3-b706-b914f4bd002e:4621)
    at <anonymous>:3:100
    at E.z.<computed> (eval at exec_fn (www.ea.com/:1), <anonymous>:43:442)
```

**Comment by Mardaneus86** [comment]
Enum name was changed. Can't test it properly since the account I got from a community member doesn't have transfer market access.

Expect a 2.0.4 release soon.
