### ISSUE TITLE
Question: How to fetch trade id

### ISSUE THREAD

**Issue by ndoulgeridis** [Mardaneus86/futwebapp-tampermonkey#255]
Does anyone know to get the tradeId of each auction? There is no hidden input in HTML but I wonder how these are generated when you post a new player or when you remove players from sold or watched players.

Has anyone any idea of how to grab each auction's tradeID? Is this generated somehow from JS?

**Comment by Mardaneus86** [comment]
This isn't the place for questions, please reach out in the Gitter channel so maybe someone can help you over there.

If it is an actual feature request, describe the functionality that is wanted instead.
