### ISSUE TITLE
Updated to 2.0.3, working as before temporarily, then stopped working again.

### ISSUE THREAD

**Issue by niiiptune** [Mardaneus86/futwebapp-tampermonkey#256]
Tried a few hours ago and didn't work. Closed my browser and tried again just now, the issue remains. Appreciate the effort to check!

**Comment by horotec** [comment]
try reinstalling, seemed to fix the issue for me.

**Comment by niiiptune** [comment]
Oh I seem to be banned from FUTBIN because of using the tool. Will send an email to them.

**Comment by Mardaneus86** [comment]
Release [2.0.5](https://github.com/Mardaneus86/futwebapp-tampermonkey/releases/tag/2.0.5) should prevent calling Futbin too often. Usually you get unbanned automatically if you wait a day or so (disable the Futbin integration for a while in the app to do so).

The script used to call futbin as well for non-player items, which is now prevented.
