### ISSUE TITLE
Futbin price not displaying for me

### ISSUE THREAD

**Issue by fluggums** [Mardaneus86/futwebapp-tampermonkey#30]
Hey guys, I'm running this on firefox and what doesnt seem to be working for me is the search lowest bin, show club / transfer list value, and the display of the futbin price.  Any idea on how I can fix this?

**Comment by Mardaneus86** [comment]
Did you refresh the app after installing the scripts? Can you make sure the scripts are loaded at all?

**Comment by fluggums** [comment]
I can confirm that the scripts are loaded, and I tried refreshing the app after installing but no luck to either

**Comment by renard0** [comment]
I found that scripts doesn't work in Greasemonkey while its fine in Tampermonkey

**Comment by renard0** [comment]
@fluggums do you use Greasemonkey or Tamper?

**Comment by Mardaneus86** [comment]
Yeah I've just noticed the same thing. I was assuming the scripts would work in Greasemonkey as well. Will investigate further why this happens.

**Comment by Mardaneus86** [comment]
I will edit the Readme to make sure people use Tampermonkey in Firefox as well. As I can't seem to debug GreaseMonkey scripts, I can't really support it.

If someone finds a workaround or a way to debug, please let me know in the Gitter channel.
