### ISSUE TITLE
Replace 'Mutation events' with  'MutationObserver'

### ISSUE THREAD

**Issue by renard0** [Mardaneus86/futwebapp-tampermonkey#31]
Some of the scripts use 'Mutation events' such as 'DOMNodeInserted'.
'Mutation events' are no longer the part of the standard and its recommended to use 'Mutation Observers' instead.
https://developer.mozilla.org/en-US/docs/Web/Guide/Events/Mutation_events

**Comment by Mardaneus86** [comment]
Feel free to do a PR to replace the mutation events with mutation observers.

It currently still works, so not giving it priority for now.
