### ISSUE TITLE
Feature request: number of players in each league and country

### ISSUE THREAD

**Issue by debugman5** [Mardaneus86/futwebapp-tampermonkey#32]
I think it would be helpful for those SBCs to see a spreadsheet of how many players I have divided to leagues and divided to countries. Maybe even divided to card version if possible (gold, silver... rare/not rare)

**Comment by Mardaneus86** [comment]
You want to download all your club players with their metadata as a spreadsheet so you can filter using Excel for example?

If not, please provide a mockup of how you see it.

**Comment by Kyderman** [comment]
@Mardaneus86 

I assume this is basically running every single combination of search on the cub and then showing the numbers for each? But limited to country, league and card version.

e.g
Prem
England - Gold - 12
England - Silver - 4
...
...
Brazil - Gold - 3
....
English Championship
England - Gold - 1
England - Silver - 77
..

**Comment by Mardaneus86** [comment]
Maybe it's easier to create a button that would download it as a CSV file, that way people can sort/filter and do whatever they want with it. Prevents a lot of hassle in the web app itself.

As for timing, it could indeed use the same calls as the Futbin Club Worth script. Unfortunately separate scripts do not have the ability to read each others `GM_setValues`. Maybe it's helpful to make a Club Statistics script that combines the Club Worth and this feature request.

**Comment by Kyderman** [comment]
+1
Yes, club statistics would be a great idea.

Seems like a logical thing to merge.

I might have some time later to do this depending on how I feel. If you've got a quick tutorial on new page creation within the web app, I could give this a shot.

**Comment by Mardaneus86** [comment]
Take a look at [the wiki about creating new UI pages](https://github.com/Mardaneus86/futwebapp-tampermonkey/wiki/Creating-new-UI-pages).

**Comment by GamerAsh** [comment]
Would be possible to get player information from the trade pile such as nationality and league? This would be super helpful when you have duplicate bronzes you want to use in the upgrade SBCS. You could filter them by country or leauge for the chem reasons.

**Comment by Kyderman** [comment]
@GamerAsh, yes it is possible.

This reminds me that the futbin club worth needs to look at the trade pile too, and any club information screen should also look at the trade pile.

**Comment by debugman5** [comment]
I meant something similar (preferably better)  to what we have in the game itself inside your club tab, where you can see how many players you have in each league

**Comment by Mardaneus86** [comment]
Fixed in [v0.2.0](https://github.com/Mardaneus86/futwebapp-tampermonkey/releases/tag/v0.2.0)
