### ISSUE TITLE
FUT Show Contract and Fitness: Not working for Inform cards

### ISSUE THREAD

**Issue by omasseau** [Mardaneus86/futwebapp-tampermonkey#34]
This script does not work for Inform cards.
I guess it's because the text is in black, which is of course invisible on a black background :p

**Comment by Mardaneus86** [comment]
Changed the CSS so contracts and fitness are shown in white when the card is of type OTW, TOTW, TOTS or TOTY.

PS: use the issue template for future issues, that makes it easier to get a quick view on which script it is about.
