### ISSUE TITLE
auto confirm buy now

### ISSUE THREAD

**Issue by sharaku17** [Mardaneus86/futwebapp-tampermonkey#36]
### Expected behavior:
When Buy Now is clicked, the confirmation Pop Up shouldnt pop up and be confirmed directly instead
### Current behavior:
Whenever the Buy Now tab is clicked the Pop up still comes and is not confirmed.
Does it only work for bidding? If yes than maybe the name is a little bit Confusing with "FUT Confirm Buy Now"

### Metadata:
- **Script name:**  FUT Confirm Buy Now
- **Script version:** 0.1.2
- **Browser:** Firefox
- **OS:** Mac OS

**Comment by Mardaneus86** [comment]
Can you try if [v0.1.1](https://github.com/Mardaneus86/futwebapp-tampermonkey/raw/2315b87f8db397b5d0838779f35b05b2894dc033/confirm-buynow-dialog.user.js) has the expected behaviour? If so, it might be related to the mutation observer change I did yesterday.

**Comment by Mardaneus86** [comment]
Can you confirm that you are using Tampermonkey? I've dropped GreaseMonkey support because it is not debuggable in any way.

**Comment by renard0** [comment]
Its not about Greasemonkey. Already found the bug. Will do PR soon
