### ISSUE TITLE
Bug: transfer-search-increase-list-size.user

### ISSUE THREAD

**Issue by debugman5** [Mardaneus86/futwebapp-tampermonkey#38]
### Expected behavior:
list size of transfer size should be 30

### Current behavior:
list size is 15

**Comment by Mardaneus86** [comment]
I'm unable to try this out for a few days, if anyone cares to check this out by all means do.

**Comment by Mardaneus86** [comment]
Fixed by resetting the list size on every screen change instead of only on login.
