### ISSUE TITLE
Change Futbin console/pc price source

### ISSUE THREAD

**Issue by SubNoizey** [Mardaneus86/futwebapp-tampermonkey#41]
It would be nice if we could use settings to select the source, either xbox/ps4 or pc as the futbin price option.

In the "Show Futbin player price" script.

edit: Oh.. I just checked the source and it looks like it does this already by picking what platform you're on. I guess it's just Futbin being slow to update the PC bin prices

feel free to close.

**Comment by Kyderman** [comment]
Just so you know, Futbin can be slow.

There is a pull request to show the time in which the price was last updated.

So soon you will be able to see.
