### ISSUE TITLE
Suggestion - FUT Show Futbin Player Price, change coin colour

### ISSUE THREAD

**Issue by SubNoizey** [Mardaneus86/futwebapp-tampermonkey#43]
At the moment the columns of coins and prices melt into one another and at first glance it's difficult to differentiate them when looking at a full screen of cards (especially when it takes a second or two to pop in). 

Is it possible to do this?

https://i.imgur.com/NsIYiDJ.png

Here's the green coin if it's possible, I'm also sure it'll look better than my quick mock up as you'll be able to do it via css.
https://i.imgur.com/eYmRCZ4.png

**Comment by omasseau** [comment]
Would be useful indeed :)

**Comment by Mardaneus86** [comment]
If anyone wants to create this, it's quite an easy PR.

One remark, the green icon could be confused for FIFA coins, so another color might be more appropriate.

**Comment by SubNoizey** [comment]
Any suggestions? I'll play around with a few colours and see

**Comment by Mardaneus86** [comment]
Alright, without introducing new images to download, this is the CSS approach I'm wanting to take:

```css
-webkit-filter: hue-rotate(165deg);
filter: hue-rotate(165deg);
```

This makes the coin stack image in a blue tint.
