### ISSUE TITLE
FUT Confirm Buy Now Dialog doesn't do anything

### ISSUE THREAD

**Issue by Blank-23** [Mardaneus86/futwebapp-tampermonkey#44]
### Expected behavior:
The script should auto-confirm the confirmation popup when I click "Buy Now" in the FUT Web app

### Current behavior:
Clicking "Buy Now" opens the popup and does not confirm it. 

I installed TamperMonkey extension and added the script to it. TamperMonkey says the script is "On".

### Metadata:
- **Script name:** FUT Confirm Buy Now Dialog
- **Script version:** v0.1.2
- **Browser:** Chrome
- **OS:** Windows 10

**Comment by Mardaneus86** [comment]
Closing since this functionality isn't available anymore in the new version.

Added an issue (#96) to create this feature in a future release.
