### ISSUE TITLE
Seperate scripts or single script?

### ISSUE THREAD

**Issue by Mardaneus86** [Mardaneus86/futwebapp-tampermonkey#47]
PR #45 got me thinking, and I would like to discuss this new idea before acting on it.

Having many loose scripts looks good at first sight, but gets cumbersome soon from a development perspective. If you want two pieces of functionality that look very similar but have a different purpose, either a lot of code needs be duplicated. The other option is that the scripts can be merged with a branch for the two functionalities. However, there is currently not a good way to set options for each script, because `GM_setValue`/`GM_getValue` can only set and get data from the script they are running in.

A solution to this problem could be to provide all the current scripts as a single scripts, where you can enable and disable each option. The Settings script provides an example of where you could enable and disable options. This way we can be sure that you either have the default settings or only enable what you want, because the settings script would also be included. 

What do you guys think about this? Is a single script better for you as a user if you have in-app settings, or do you prefer separate scripts for each functionality?

**Comment by fifa2017player** [comment]
One script with settings to turn on/off specific functionality would be my preference. Thanks!

**Comment by renard0** [comment]
The other thing I think of is some basic settings scripts where general config and values could be set. But creating one script with possibility to switch needed scripts is good idea. It also allow to reduce code duplication such as getting the user platform as it can be the part of interface (utility class)

**Comment by Mardaneus86** [comment]
That basic settings script already exists but has some limitations as I explained in the original post.

I’ll create a separate branch for this soon.

**Comment by debugman5** [comment]
Do you mean there will be a single script that will load the other scripts from urls or all the code will be in a single script?

**Comment by Mardaneus86** [comment]
All code within a single script. Bundled via webpack for example, so we can also use ES6 syntax.
