### ISSUE TITLE
[Suggestion] Trade Pile Value

### ISSUE THREAD

**Issue by ismailpatel95** [Mardaneus86/futwebapp-tampermonkey#49]
### Trade Pile Value

These scripts are excellent, particularly for a programming newbie like myself. A suggestion I have is if one can develop a script to determine the value of the Trade Pile at any given time.

**Comment by renard0** [comment]
What do you mean on Trade Pile value?

**Comment by ismailpatel95** [comment]
I meant the value of items for sale at any instance. Its a pain trying to figure it out when you have like 20+ items for sale.

**Comment by Mardaneus86** [comment]
Based on Futbin value I suppose? That should be doable...

**Comment by Kyderman** [comment]
Ill be updating the futbin club worth to include the trade pile. in its calculations.

We are looking at making a "club information page" which would have this sort of information in a nice seperated out manner.
