### ISSUE TITLE
[Suggestion] Auto List items

### ISSUE THREAD

**Issue by erhangunay** [Mardaneus86/futwebapp-tampermonkey#50]
Is it possible to add a function that lists all items on the transfer list with the lowest bin?

**Comment by Mardaneus86** [comment]
Currently not, there is only a script that relists expired auctions with the same prices.

Question would be which BIN price to take. Futbin sometimes has a large window between price updates, so you could potentially sell players way under their price.

**Comment by erhangunay** [comment]
You also have a script to check the minimum bin. Doesn't that use the market to find the minimum bin? And thank you for your answer

**Comment by Mardaneus86** [comment]
Yes, it does search the market. However, it does multiple searches to find the min bin. So that's not a viable option to use for relisting many players.

**Comment by erhangunay** [comment]
As you say :) Okay thanks again

**Comment by Mardaneus86** [comment]
Closing the issue for now, as I want to use #42 as a starting point for this. So you could pick the start price with some kind of cool down factor. Minimizing list/BIN price every X tries, and eventually discard or return to club if it fails to sell.
