### ISSUE TITLE
Nothing works in Windows 10

### ISSUE THREAD

**Issue by debugman5** [Mardaneus86/futwebapp-tampermonkey#51]
Nothing is really working except UI (show BIN button and settings page) in both Chrome and Opera browsers.

It's really strange... on my mac its working..

**Comment by Mardaneus86** [comment]
Can you see any script errors in the Chrome console?

**Comment by debugman5** [comment]
I see some errors counter, but I am not familiar with how to see them, clicking on the indicator does nothing

**Comment by debugman5** [comment]
I think I got it:
`utas.external.fut.ea.com/ut/game/fifa18/user/accountinfo?filterConsoleLogin=true&sku=FUT18WEB&returningUserGameYear=2017&_=1508190071636:1 GET https://utas.external.fut.ea.com/ut/game/fifa18/user/accountinfo?filterConsoleLogin=true&sku=FUT18WEB&returningUserGameYear=2017&_=1508190071636 465 (465)
utas.external.s3.fut.ea.com/ut/game/fifa18/user/accountinfo?filterConsoleLogin=true&sku=FUT18WEB&returningUserGameYear=2017&_=1508190071638:1 GET https://utas.external.s3.fut.ea.com/ut/game/fifa18/user/accountinfo?filterConsoleLogin=true&sku=FUT18WEB&returningUserGameYear=2017&_=1508190071638 465 (465)`
`compiled_1.js?_=171400:25 GET https://www.easports.com/fifa/ultimate-team/web-app/css/ajax-loader.gif 403 (Forbidden)`

**Comment by debugman5** [comment]
Well, anyway restart fixed the scripts, I still see those errors, but the script now works

**Comment by Mardaneus86** [comment]
Alright, closing the issue if it’s resolved.

Will look into those errorcodes to see if it has anything to do with these scripts.

**Comment by Mardaneus86** [comment]
These 465 errors also show without using Tampermonkey, so it's an issue on EA's part. Nothing to be concerned about.
