### ISSUE TITLE
[request] disable visibilitychange handlers

### ISSUE THREAD

**Issue by fifa2017player** [Mardaneus86/futwebapp-tampermonkey#53]
### Expected behavior:
If you hide the webapp browser tab completely by switching to another tab, the webapp goes into this mode where some elements aren't visible or displayed, thus using selectors to select elements won't work. The webapp code seems to be setting the visibilitychange event handler on the document whenever you enter some views? Not sure how to disable it completely.

### Current behavior:
Give a detailed explanation of the current behavior.

### Metadata:
- **Script name:** 
- **Script version:**
- **Browser:**
- **OS:**

**Comment by Mardaneus86** [comment]
When does this create an issue? I need some example to know how to "fix" this.

**Comment by fifa2017player** [comment]
It seems none of the current scripts are actually affected by this, because they either require the user to go to a particular screen to trigger, or use the data service directly, instead of simulating clicking on various buttons to go to particular screens.

In my use case, I have written some code to tap the buttons to go into particular screens so that I can trigger the scripts, and the visibilitychange is causing the buttons to be hidden and thus I can't change screens.

Since this isn't affecting the scripts provided, I will close out the issue and find some other workarounds. Thanks for taking a look!
