### ISSUE TITLE
[Suggestion] Relist item with specific hours

### ISSUE THREAD

**Issue by debugman5** [Mardaneus86/futwebapp-tampermonkey#54]
It would be great if there was a dropdown selector to select for how long to re-list all the items in the trade pile.

p.s. When I will have more time, I will learn JS (I'm a developer, just not a JS developer) and maybe will be able to contribute.

**Comment by Kyderman** [comment]
^ in terms of trading, you want to be working in 1 hour increments. For a variety of reasons

**Comment by debugman5** [comment]
Yeah, but if you don't want to use the auto relist script, its better to relist the items at night for 6 hours

**Comment by omasseau** [comment]
Indeed being able to relist at night for 6 hours in a single click would be very useful :)

**Comment by Mardaneus86** [comment]
Decided not to do any automation with this script.
