### ISSUE TITLE
Suggestion: List item for FUTBIN BIN

### ISSUE THREAD

**Issue by captain-nev** [Mardaneus86/futwebapp-tampermonkey#58]
Would be an easy way to get list players a little more quickly.

**Comment by Kyderman** [comment]
Hi, we are working on a feature that encompasses this sort of stuff.

So hopefully once that is done we can release the features we have "discovered" from it.

**Comment by Mardaneus86** [comment]
Since Futbin is outdated most of the time, so using those prices wouldn't be useful. As Kyderman said, there is another approach using the "search minimum BIN" script.

**Comment by Kyderman** [comment]
Update:

I will be looking at the logic for listing players tonight for another part of the project under development.

Once everything is working, it would be possible to get a script up for listing a player and just below min bin (probably a button near the "list button" that says "list for min bin".

**Comment by Mardaneus86** [comment]
We should add a percentage setting based on min BIN price. People need to have the choice to sell at 110% or 90% of min BIN.

**Comment by Bendecks** [comment]
This sounds so exiting! Did you guys drop this enhancement, or still working on it? I have patience, was just curious :-D

**Comment by Mardaneus86** [comment]
Still working on it. Framework for the single script with in-app customization is nearly finished. The Futbin prices are being updated more frequently now as well.

**Comment by Bendecks** [comment]
Awesome. Also, is the selling price based on the lowest BIN or an average of the 3 lowest BINS? The latter would avoid selling cards at a price way to low.

**Comment by Mardaneus86** [comment]
In my current version it's based on the mean of the lowest 3 prices, then rounding to the nearest round price (based on thz FUT price tiers). Have been playing with a mean/median with the prices of the lowest 3/5/10 results and 3 provided the best results on average.

It's supposed to become a user setting that's defaulted to 3.

**Comment by Bendecks** [comment]
That's sounds great, can't wait :-D

**Comment by Bendecks** [comment]
Okay, maybe I'm not that patient 😃

Do you have a rough estimate of when this is ready? 😉

**Comment by Mardaneus86** [comment]
For merging the scripts I do have an estimate, I should have something running by the end of this weekend. It won't have user settings yet though, although the framework for it is nearly ready. I'm still working on the queuing of scripts right now.

**Comment by Bendecks** [comment]
Sounds really awesome, thx for the fast reply!

**Comment by Bendecks** [comment]
This didn't make it in to the release last night, did it?

**Comment by Mardaneus86** [comment]
It did make it into the release, although I did take a little different approach for now. When you check the minimum BIN, it adjusts the prices in the quick list panel accordingly. I have some clean up work to do in the issue list.

So this is essentialy fixed with [v0.1.1](https://github.com/Mardaneus86/futwebapp-tampermonkey/releases/tag/v0.1.1).

**Comment by Bendecks** [comment]
Yeah, I see how it's working now, and it works very well. Thank you!
