### ISSUE TITLE
Automatically clear expired items in transfer targets

### ISSUE THREAD

**Issue by fifa2017player** [Mardaneus86/futwebapp-tampermonkey#60]
### Expected behavior:
Is there a script that automatically clear expired items in transfer targets, similar to how there is one to automatically clear items that are sold?

### Current behavior:
Give a detailed explanation of the current behavior.

### Metadata:
- **Script name:** 
- **Script version:**
- **Browser:**
- **OS:**

**Comment by Mardaneus86** [comment]
Good idea!

**Comment by Mardaneus86** [comment]
Decided not to do any automation with this script.
