### ISSUE TITLE
Scripts don't work on phone layout

### ISSUE THREAD

**Issue by debugman5** [Mardaneus86/futwebapp-tampermonkey#62]
Scripts stopped working. no futbin price, search bin price button is showing, but not working.

I tried reboot, but it didn't help.

Here are the errors I see in the console:

`utas.external.fut.ea.com/ut/game/fifa18/user/accountinfo?filterConsoleLogin=true&sku=FUT18WEB&returningUserGameYear=2017&_=1508617606696:1 GET https://utas.external.fut.ea.com/ut/game/fifa18/user/accountinfo?filterConsoleLogin=true&sku=FUT18WEB&returningUserGameYear=2017&_=1508617606696 465 (465)
utas.external.s3.fut.ea.com/ut/game/fifa18/user/accountinfo?filterConsoleLogin=true&sku=FUT18WEB&returningUserGameYear=2017&_=1508617606698:1 GET https://utas.external.s3.fut.ea.com/ut/game/fifa18/user/accountinfo?filterConsoleLogin=true&sku=FUT18WEB&returningUserGameYear=2017&_=1508617606698 465 (465)`

I don't think it's related, am I right?

**Comment by Mardaneus86** [comment]
The 465 response codes are "normal". They are not related to the scripts not working.

**Comment by debugman5** [comment]
So what's the problem?

**Comment by Mardaneus86** [comment]
I'd need a windows 10 PC to try this (which I don't have), so without extra information I can't tell. You already mentioned something similar in #51. Did you try a restart already (since that helped before)?

Try to make sure the scripts are loaded properly. You can include a `console.log` statement at the top of the futbin price script (below the tampermonkey headers).

Also, make sure you are using Tampermonkey instead of Greasemonkey.

**Comment by debugman5** [comment]
Its actually a windows on mac, but I guess its not important.

I added the `console.log` to the top of the script, and its called, but the function of showing the price is not.

**Comment by Mardaneus86** [comment]
Can you provide some extra info I can use for investigating:
- browser and version?
- script and their version number?
- greasemonkey or tampermonkey?

**Comment by debugman5** [comment]
- Chrome Version 62.0.3202.62 and Opera 48.0.2685.50
- Show futbin price script version 0.2.7 (most of the scripts do not work)
- Tampermonkey version 4.4

**Comment by Kyderman** [comment]
@Mardaneus86 

This also relates to my issues.

**Comment by Mardaneus86** [comment]
This might be related to changes on EA's side, investigating with the help of @Kyderman.

**Comment by Mardaneus86** [comment]
Does this still apply to you @debugman5? Based on your other reports you got the scripts working.

**Comment by Mardaneus86** [comment]
Please reopen if the issue still exists.

**Comment by debugman5** [comment]
@Mardaneus86  No, its still not working for me on Windows, only on Mac OS.

**Comment by debugman5** [comment]
I think I know the issue, but first a question: does anyone have the navigation panel on the bottom and the scripts works for him?

**Comment by Mardaneus86** [comment]
Navigation panel on the bottom? As far as I know it's supposed to be on the left.

**Comment by debugman5** [comment]
yes, on mac its always on the left, but on windows its on the bottom. So, when I open the developer tools and make it wide enough, the navigation goes to the left, and everything works.

Is there some code I can add to one of the scripts that will make the navigation be on the left?

**Comment by debugman5** [comment]
It seems that in windows it look like the companion app. the drop down popovers (selector) looks just like in the Android app

**Comment by Mardaneus86** [comment]
Aha, this has to do with your screen width being less than 767px at startup. The app will adjust to the phone layout then, which doesn't have all the functionality and UI elements.

So workaround for now: always start at a bigger size than 767px width.

When I merge all scripts together, I can fix this in one place so you never get the phone layout when using this with the Tampermonkey scripts.

**Comment by debugman5** [comment]
@Mardaneus86 But it works when I making the window smaller (with the developer tools) and not bigger. Maybe its screen resolution setting?

**Comment by Mardaneus86** [comment]
It all depends on what size the screen has when you start the web app. The web app looks at window width, so the width of the developer tools are not accounted for.

Either way, when you get a phone layout the scripts might not work because of missing UI elements. This actually has nothing to do with you computer being Windows or Mac.

**Comment by Straitlake** [comment]
I can confirm the issue was caused by the screen width, i managed to solve the issue by changing my resolution to 1366x768.

**Comment by Mardaneus86** [comment]
Fixed in [v0.2.1](https://github.com/Mardaneus86/futwebapp-tampermonkey/releases/tag/v0.2.1).
