### ISSUE TITLE
Search bin price for special player

### ISSUE THREAD

**Issue by debugman5** [Mardaneus86/futwebapp-tampermonkey#63]
Is it possible that the search bin button will search the specific card type of the player?

**Comment by Mardaneus86** [comment]
Everything is possible, but everyone has different criteria (same position, same chemistry style, ...) so this will be quite hard to get right for everyone.

**Comment by debugman5** [comment]
Is there even a way to search for an IF specifically, or only special in general?

**Comment by Mardaneus86** [comment]
No, you can search for "Specials", but not for TOTM or TOTW specifically. You're restricted to what the UI already provides.

**Comment by Mardaneus86** [comment]
Code contained a bug when rare type was TOTW. Resolved with commit 712e263.
