### ISSUE TITLE
Show futbin price not working in transfer list after web app update

### ISSUE THREAD

**Issue by ilihasj** [Mardaneus86/futwebapp-tampermonkey#67]
### Expected behavior:
It showed the price in the transfer list before the update

### Current behavior:
It no longer shows the price in the transferlist

### Metadata:
- **Script name: FUT Show Futbin Player price 
- **Script version: latest
- **Browser: Chrome
- **OS: MacOS

**Comment by Feigenstaub** [comment]
can confirm that.
and the "search min bin" label is corrupt in search results

**Comment by Mardaneus86** [comment]
Yes, I'm working on the fix. Will be updated within an hour.

**Comment by Mardaneus86** [comment]
Alright, fixed with commit 5c87033. Pushed v0.3.0 to the repository. Reopen if you still have issues after updating.

**Comment by debugman5** [comment]
Stopped working on unassigned items as well. I did a fix, do you want me to upload?

**Comment by debugman5** [comment]
Here's the fix:

[showFutbinPrice-unassigned-fix.txt](https://github.com/Mardaneus86/futwebapp-tampermonkey/files/1416245/showFutbinPrice-unassigned-fix.txt)

**Comment by ilihasj** [comment]
Thank you for fixing it so quickly!
