### ISSUE TITLE
auto confirm buy now issue

### ISSUE THREAD

**Issue by TommasoBassini** [Mardaneus86/futwebapp-tampermonkey#71]
when the player has already been bought by someone else, anything goes in a loop

- Script name: FUT Confirm Buy Now Dialog 
- Script version:  0.1.3
- Browser: Chrome
- OS: win 10

**Comment by Mardaneus86** [comment]
I've noticed that as well. Thanks for reporting.

**Comment by Mardaneus86** [comment]
Closing since this functionality isn't available anymore in the new version.

Added an issue (#96) to create this feature in a future release.
