### ISSUE TITLE
Futbin prices not showing in club's search filters

### ISSUE THREAD

**Issue by debugman5** [Mardaneus86/futwebapp-tampermonkey#73]
It stopped working because of the fix for stopping the interval when exiting the relevant page.

I did a fix if want it: 
[FUT Show Futbin player price.user.txt](https://github.com/Mardaneus86/futwebapp-tampermonkey/files/1421365/FUT.Show.Futbin.player.price.user.txt)

**Comment by Mardaneus86** [comment]
Please submit these fixes as PR's instead of separate issues. It's very hard to keep track of what you changed this way.
