### ISSUE TITLE
[Suggestion] Include FUTBIN price in search filter

### ISSUE THREAD

**Issue by Feigenstaub** [Mardaneus86/futwebapp-tampermonkey#74]
Is there a way to include the FUTBIN price to search for players on the market?

So you can easy find players who are currently listed below the latest futbin price. 
A request could be: Find all players which BIN price is >20% under latest futbin price.

**Comment by Mardaneus86** [comment]
That would require a big alteration of the search screen. Or how would you see this implemented?

**Comment by Feigenstaub** [comment]
idk how complicate it is to modify the search criteria, could be easier to create a new (extra) algorithm / search.

**Comment by Mardaneus86** [comment]
Since you can already find the futbin price or min bin search and enter those values quite easily, this won't get high on the priority list. Feel free to submit a PR though.

**Comment by Feigenstaub** [comment]
yes u can find it for a specific player but you dont know who is currently cheap on the market. That's what u will find out with the search. But maybe it would be too OP.

**Comment by Mardaneus86** [comment]
With the search criteria that the web app supplies, this is not possible without sending a lot of requests. While I can see the added value, it is very hard to achieve.

Cleaning up the issue list for the FIFA 19 update.
