### ISSUE TITLE
[Request] Expired auctions notificaiton

### ISSUE THREAD

**Issue by bertrand2012** [Mardaneus86/futwebapp-tampermonkey#76]
Can anyone help me out with editing the 'FUT Auto Relist Expired Auctions' script to not actually relist them but just to give a notification when they expire?

Thanks to any help :P

**Comment by Mardaneus86** [comment]
Remove https://github.com/Mardaneus86/futwebapp-tampermonkey/blob/master/auto-relist-expired-auctions.user.js#L27 from the script. You can remove the timeout from the notification to get it persistent.
