### ISSUE TITLE
[Suggestion] Buy now with a double click

### ISSUE THREAD

**Issue by YounesElm** [Mardaneus86/futwebapp-tampermonkey#77]
For you guys, it's possible to integrate a script who buy a player in the search result with a simple double click ? 

Thanks, and good job for others scripts !

**Comment by Mardaneus86** [comment]
That's certainly possible. Will consider adding this in the merged version of the scripts. Can't give an ETA yet.

**Comment by arriff** [comment]
+1

**Comment by Mardaneus86** [comment]
I think this might be fairly error prone. Will keep it into consideration while testing for the FIFA 19 release.

Cleaning up the issue list for the FIFA 19 update.
