### ISSUE TITLE
[Suggestion] Method for players double in club

### ISSUE THREAD

**Issue by Mit010** [Mardaneus86/futwebapp-tampermonkey#78]
### Current behavior:
When you have a double player, the player needs to be sent to the transferlist, listed on the transferlist or quicksold. I am not a programmer, but it woud come in very handy if it was easier to locate these players in the club so they can be put in to the bronze/silver/gold upgrade SBCs.  Maybe it would be possible to tag double players on the transferlist and have the names / positions on the side of the sbc or something? Or to starrt such a SBC and then be able to go to the transferlist and tag them there? So you would pick the player in the transferlist instead of going into the club and searching for them there.

**Comment by Mardaneus86** [comment]
Sounds like a good idea to use SBC's in that way. Needs some good algorithm to make the team meet the requirements though. Or perhaps use them for upgrade SBC's.

**Comment by Mardaneus86** [comment]
Would require a lot of effort to achieve. So postponing unless a lot of people request this feature.

Cleaning up the issue list for the FIFA 19 update.
