### ISSUE TITLE
gets notification when i put an item on the market

### ISSUE THREAD

**Issue by bertrand2012** [Mardaneus86/futwebapp-tampermonkey#80]
### Expected behavior:
Give notification when I sell an item EDIT: WHEN I NEED TO RELIST AN ITEM*

### Current behavior:
Gives me a notification when I list an item (does still give me a notification when I sell an item though)

### Metadata:
- FUT Auto Relist Unsold Transfers (but modified)
- I'll just give the full script
```
(function () {
  'use strict';

  gAuthenticationModel.addListener(models.AuthenticationModel.EVENT_AUTHENTICATION_SUCCESSFUL, this, function () {
    setInterval(function () { repositories.Item.getTransferItems().observe(this, _handleExpiredAuctions); }, 60000);

    var _handleExpiredAuctions = function handleExpiredAuctions(observer, data) {
      if (data.items.filter(function (d) { return d.state === enums.ItemState.FREE && d._auction.buyNowPrice > 0; }).length > 0) {

        // Refresh screen if we are on the transfer list screen
        if (typeof gNavManager.getCurrentScreenController()._controller == "TransferListLandscapeViewController") {
          gNavManager.getCurrentScreenController()._controller._listController._requestItems();
        }

        GM_notification({
          text: "Relisted expired auctions",
          title: "FUT 18 Web App",
          onclick: function () { window.focus(); },
        });
        console.log("Automatically Relisted Expired Auctions");
      }
    };
  });
})();
```
- Chrome
- Macbook

**Comment by Mardaneus86** [comment]
What am I looking at exactly? The code you provided gives you a permanent notification if there are items that can be relisted in your tradepile, but does not relist by itself. I can't see how that fits the expected behavior you described.

https://github.com/Mardaneus86/futwebapp-tampermonkey/blob/master/remove-sold-auctions.user.js gives notifications when items are sold, that fits your expected behavior.

**Comment by bertrand2012** [comment]
@Mardaneus86 Sorry about that I didn't mean to say when I sell an item, but when I need to relist an item. Currently, this script does do that but it also gives me the same notification oddly when I list an item.

**Comment by Mardaneus86** [comment]
Perhaps the Item repository isn't updated instantly in that case, it only fetches new items once every minute.

You can reset that cache with the following code:
```js
repositories.Item.setDirty(enums.FUTItemPile.TRANSFER);
repositories.Item.getTransferItems();
```

You can use the following enums in `setDirty`:
- enums.FUTItemPile.PURCHASED
- enums.FUTItemPile.TRANSFER
- enums.FUTItemPile.INBOX

If you want to reset them all at once, use this command:
```js
repositories.Item.reset();
```
