### ISSUE TITLE
scripts safe?

### ISSUE THREAD

**Issue by cm4faNN** [Mardaneus86/futwebapp-tampermonkey#81]
not sure if this is the right way to ask this, of if it is even allowed, so I'm sorry in advance if I can't ask it like this, but my only question is if the scripts presented here (which I love, by the way...) are safe to use and won't risk my account being banned by EA?

Thanks a lot for all your work guys.

Cheers.

**Comment by Mardaneus86** [comment]
As stated in the Readme, using these scripts is against the ToS of EA. Any addition/alteration to their website can be a reason to get banned. However, looking at it realistically, you only risk a ban if you automate the app to such a degree that you get an unfair advantage (like the use of an autobuyer/BIN sniping). But before you risk getting banned, you will first see a lot of captcha screens.

The scripts that are in the `master` branch are fairly safe to use, however I can't guarantee that EA won't take actions against the use of these scripts.
