### ISSUE TITLE
Problem with "Search minimum BIN"

### ISSUE THREAD

**Issue by NoOpinionOo** [Mardaneus86/futwebapp-tampermonkey#82]
I tried to search for minimum BIN to compare it with the Buy Now price.
If I do so the listed items are instantly expirering. In fact they aren´t expired. If I reload the web app I can place my bid. This didn´t happen in the version with seperated scripts.

**Comment by Mardaneus86** [comment]
Thanks for reporting, will look into it asap!

**Comment by Mardaneus86** [comment]
Fixed in [v0.2.0](https://github.com/Mardaneus86/futwebapp-tampermonkey/releases/tag/v0.2.0).
