### ISSUE TITLE
v0.2.0 not working (Tampermonkey does not load the script)

### ISSUE THREAD

**Issue by dominielus** [Mardaneus86/futwebapp-tampermonkey#83]
The single scripts worked for me without problems, but today I installed the merged version of all scripts and deleted the old single one, and form that moment the script is not working.

**Comment by dominielus** [comment]
It works, Thanks Mate.

**Comment by Mardaneus86** [comment]
Yeah you are right, forgot this line during migration. Will add a comment in the release notes for now. It’s marked pre-release for a reason.

Thanks for reporting.

**Comment by dominielus** [comment]
No problem sir, glad I could help. Good job with the script!

**Comment by Mardaneus86** [comment]
Fixed in [v0.2.1](https://github.com/Mardaneus86/futwebapp-tampermonkey/releases/tag/v0.2.1).
