### ISSUE TITLE
Every time, the tool automatically back to Relist at BIN price even I unselected it last run 

### ISSUE THREAD

**Issue by stefanis5454** [Mardaneus86/futwebapp-tampermonkey#85]
### Expected behavior:
Save the selection 

### Current behavior:
Give a detailed explanation of the current behavior.

### Metadata:
- **Script name:** 
- **Script version:**
- **Browser:**
- **OS:**

It is really really annoying!!!!!!!!

I dont need the function of  Relist at BIN price! I just need to relist as the price I listed before.

**Comment by stefanis5454** [comment]
I had been forced to relist manually more than 90 cards at the price I want more than 5 times, it is really really big big problem!

**Comment by Mardaneus86** [comment]
Which version are you using?

**Comment by Mardaneus86** [comment]
Taken a quick look, and it appears the UI isn't initialised properly after disabling the setting. The setting is stored properly. Will probably release a new version tonight.

For now, you can disable the setting entirely and use https://openuserjs.org/scripts/Mardaneus86/FUT_Auto_Relist_Unsold_Transfers in conjunction with the current script until the new version is released.

**Comment by Mardaneus86** [comment]
Fixed in [v0.2.2](https://github.com/Mardaneus86/futwebapp-tampermonkey/releases/tag/v0.2.2).
