### ISSUE TITLE
How I use This?

### ISSUE THREAD

**Issue by renatosebben** [Mardaneus86/futwebapp-tampermonkey#86]
Guys how I active the script, how I do for this buy, nothing happen when I open my webapp.

**Comment by Mardaneus86** [comment]
Follow the instructions in the [Readme about installation](https://github.com/Mardaneus86/futwebapp-tampermonkey#installation). You need Tampermonkey installed in your browser. When you click the `fut-enhancer.user.js` in the Releases page, you will get an installation request. You will then see a settings icons in the bottom right of the web app where you can enable/disable the features.
