### ISSUE TITLE
Running on Android

### ISSUE THREAD

**Issue by Bendecks** [Mardaneus86/futwebapp-tampermonkey#87]
### Expected behavior:
Is it possible to run this script on Android (Galaxy S8)?

**Comment by Mardaneus86** [comment]
Well that should be possible, since there is a Tampermonkey app for Android.

However, these scripts are not optimised for mobile use and there currently is a part in the code that forces the app to prevent using the phone layout.

**Comment by Bendecks** [comment]
I see. Is it something that you can/will add support for?

**Comment by Mardaneus86** [comment]
I am not sure if it is worth the trouble. If there are enough users that would like to use it on mobile, I can consider it.

So to the users, if you are interested leave a +1 or thumbs up here.

**Comment by Mit010** [comment]
+1

**Comment by Bendecks** [comment]
On a side note, what BIN price is used when relishing at BIN price? Futbins BIN or does the script check current prices?

**Comment by Mardaneus86** [comment]
The min bin script is used for relisting because futbin sometimes has hugely outdated data for some players.

**Comment by Bendecks** [comment]
This is great, and I can use this as a workaround for mobile use. I run the script on a server and just list players for 9000/1000 for 1 hour and let the script relist a min BIN.

**Comment by Mardaneus86** [comment]
Mobile usage is not in scope.

Cleaning up the issue list for the FIFA 19 update.
