### ISSUE TITLE
Relist unsold card one after the other. 

### ISSUE THREAD

**Issue by DeyKaz** [Mardaneus86/futwebapp-tampermonkey#93]
Your AUTO RELIST script is awesome! But i have little suggestion

Few years ago was android app FUTT14 where you could make relist all of unsold card, or you could set something like that: 
- relist first card - 30 sek/1min/10min/etc. break - relist second card - break - relist third card - break - ... 

That was helping with trading. You have 100 cards and they was spread over whole hour. 

PS
Sorry for my english.

**Comment by Mardaneus86** [comment]
Good idea! Will keep it in mind.

**Comment by Mardaneus86** [comment]
Decided not to do any automation with this script.
