### ISSUE TITLE
Problem when downloading the list of players

### ISSUE THREAD

**Issue by NapStudio** [Mardaneus86/futwebapp-tampermonkey#94]
### Expected behavior:
 futwebapp-tampermonkey/app/club/index.js 
```
case 18:
                        /* eslint-enable no-await-in-loop */

                        _core.browser._downloadFile('players.csv', ClubInfo._convertJsonToCsv(players));
                        $('#download-club-info').find('.btn-text').html('Download player list');
```
Here, at least in Firefox, I think it should be `_core.browser.downloadFile` instead of `_core.browser._downloadFile`.
When using `_core.browser.downloadFile`  it works well. I didn't try in chrome

### Current behavior:
it's given this exception when trying to download the file 

`Unhandled promise rejection 
TypeError: _core.browser._downloadFile is not a function
Stack trace:
_callee$@https://www.easports.com/es/fifa/ultimate-team/web-app/ line 3 > Function:13719:25
tryCatch@https://www.easports.com/es/fifa/ultimate-team/web-app/ line 3 > Function:9286:37
invoke@https://www.easports.com/es/fifa/ultimate-team/web-app/ line 3 > Function:9524:22
defineIteratorMethods/</prototype[method]@https://www.easports.com/es/fifa/ultimate-team/web-app/ line 3 > Function:9338:16
step@https://www.easports.com/es/fifa/ultimate-team/web-app/ line 3 > Function:13604:183
step/<@https://www.easports.com/es/fifa/ultimate-team/web-app/ line 3 > Function:13604:361
run@https://www.easports.com/es/fifa/ultimate-team/web-app/ line 3 > Function:7290:22
notify/<@https://www.easports.com/es/fifa/ultimate-team/web-app/ line 3 > Function:7303:30
flush@https://www.easports.com/es/fifa/ultimate-team/web-app/ line 3 > Function:2933:9`

### Metadata:
- **Script name:** futwebapp-tampermonkey/app/club/index.js 
- **Script version:**
- **Browser:** FIREFOX
- **OS:** WINDOWS

**Comment by Mardaneus86** [comment]
Bug confirmed, fixed in next release (ETA in a few hours).

**Comment by Mardaneus86** [comment]
Fixed in [v0.2.3](https://github.com/Mardaneus86/futwebapp-tampermonkey/releases/tag/0.2.3).

**Comment by Bendecks** [comment]
What does this do?

**Comment by Mardaneus86** [comment]
It downloads all players in your club as a CSV/excel file.
