### ISSUE TITLE
Confirm Buy Now dialog instantly

### ISSUE THREAD

**Issue by Mardaneus86** [Mardaneus86/futwebapp-tampermonkey#96]
Automatically confirm the buy now dialog. This functionality was available in the original version of these scripts, but had some issues. These can be resolved in the new setup.

**Comment by Mardaneus86** [comment]
Add the double-click option (#77) as well.

**Comment by Mit010** [comment]
This does not work for me in the new version. Both things.

**Comment by Mardaneus86** [comment]
It's an open issue on the issue list, so it hasn't been built yet.

**Comment by Bendecks** [comment]
Also "auto-login" for clicking the log in dialogue. Wasn't this available earlier?

**Comment by Mardaneus86** [comment]
Auto-login was indeed available in the initial version but had a few quirks/bugs that I haven't figured out yet. So this feature is not (yet) included in the new script.
