### ISSUE TITLE
Request: Filter by FUTBIN BIN for when searching the transfer market

### ISSUE THREAD

**Issue by kieronhughes** [Mardaneus86/futwebapp-tampermonkey#98]
Hi, I've only just started using your script and it's great, really nice work.

I was just wondering if you are able to add the ability to search the transfer market by filtering the FUTBIN BIN? Much like you can set min/max Bid or Buy Now price through the web app.

Thanks a lot!

**Comment by Mardaneus86** [comment]
Thanks for the kind words.

Currently the scripts look up the Futbin price for a specific player. Unfortunately Futbin does not provide any API that we could use to implement this request, as far as I am aware of.

However, I'm open for suggestions on how this could be accomplished.

**Comment by Mardaneus86** [comment]
Since Futbin doesn't provide any API for this, it can't be accomplished.
