### ISSUE TITLE
REQUEST: Watchlist Refresher

### ISSUE THREAD

**Issue by veredic** [Mardaneus86/futwebapp-tampermonkey#99]
### Expected behavior:
Hi, my request is about a watchlist refresher, sometimes during 10+ auctions (with 30sec less) they mix times, last position may have 5 seconds ending and first position at 30secs (because someone rebid) what I usually do to fast fix it is compare price and back (they relist in time order) OR go to transfer main page and back to watchlist, will be really good if you can develop a refresh page for watchlist, thank you for now

### Current behavior:
New feature

### Metadata:
- **Script version:** N/A
- **Browser:Chrome/firefox** N/A
- **OS:Windows** N/A

**Comment by veredic** [comment]
oh, **one extra, it will be REALLY good**, because if you check price in watchlist, to enter a bid you need to go to main page and then back, otherwise it show error message, thank you, hope you can do it :D

**Comment by veredic** [comment]
got it today :p thanks for the fast reply by the way, and waiting for your solution (cuz u're better),  just random tried and worked... added more ''cases'' to  refresher XD

**Comment by Mardaneus86** [comment]
Good to hear. Feel free to do a PR, so it will be included in the next release. My solution will probably be very similar.

**Comment by Mardaneus86** [comment]
Cleaning up the issue list for the FIFA 19 update.
